### ISSUE TITLE
Ask for confirmation isn't accurate

### ISSUE THREAD

**Issue by PandaNL** [athombv/homey#1043]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

Use the Ask for confirmation in a flow on the "and" field

_Please include detailed steps how we can reproduce the issue_

Use the Ask for confirmation in a flow on the "and" field

**What was the result?**

Almost 9/10 times I have to say minimal 2 times yes or no, because it won't pick up the first answer even when waiting a few seconds. 

**What did you expect as result?**

Pick up the first anwser directly

**Any other remarks**

Using dutch language, but the same happened on english voice settings if I remember correctly.

**Comment by Rocodamelshe** [comment]
True that.

**Comment by jjtbsomhorst** [comment]
I have to agree on this. It seems to me that this worked a lot better in 0.8 version of the firmware .

**Comment by Rocodamelshe** [comment]
Seems (at least for me) that this is solved in the latest FW.

**Comment by PandaNL** [comment]
I'm still having this problem with latest experimental firmware, same thing happens in the IOS App.

**Comment by WeeJeWel** [comment]
This should be a lot better currently.
