### ISSUE TITLE
Danfoss app E5 error + battery drain

### ISSUE THREAD

**Issue by PandaNL** [athombv/homey#1054]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

Connect Danfoss LC-13 with Danfoss app 1.0.1

**What was the result?**

Connecting works, so does the temp commando. However most of the time E5 error is displayed on the LC-13 LCD and battery gets drained very fast.

**Comment by michelderu** [comment]
I'm trying the same for the Devolo device, which essentially has the same command classes.

According to the documentation, the device goes into E5 mode if it doesn't receive the expected communication from the controller.

To be concrete:
1. I expect that the WAKE_UP_INTERVAL_SET is managed correctly by Homey
2. That means the device will send a Wakeup Notification to Homey, saying it can send/receive
3. When that happens, Homey (or the App) should read out the "mailbox" of the device. For instance the battery value.
4. If this doesn't happen, the device will go into error mode

For as far as I can see, I'm not sure that:
a. Homey acts on the Wakeup Notification (Is there a function that get's triggered anyway?)
b. If the above happens, it seems that Homey doesn't read out the "mailbox" as it should

In case point b. is the responsibility of the App: please let me know how to implement it.

(perhaps by adding the value "onWakeUp" to the pollInterval option?)

**Comment by RobinBol** [comment]
Interesting, I have tried to contact Danfoss support this week to get some more technical documentation on this E5 issue. But the scenario you describe seems reasonable, and will possibly be fixed through an update of the app.

A. Yes the driver gets an event when the device becomes awake.
B. If there are remaining GETs in the queue they will be performed once the device wakes up (in theory).

**Comment by michelderu** [comment]
Thanks Robin for your comments.

I tried to force creating remaining GETs in the queue by setting the pollIntervall of the measure_battery command class to the same (or smaller) value as the wakeUpInterval. I'm not sure anymore if that actually stopped the device from getting into error state. Will try that again right now.

I think I do remember them being executed, so that could be a solution for now.

**Comment by michelderu** [comment]
Set wakeUpInterval to 120, set pollInterval to 60. So if I understand correctly, the queue gets filled with GETs.

After say 5 minutes, clicking a button on the device seems to actually open the connection between Homey and the device and the GETs in the queue all seems to be processed at once. After this is done, the LCD changes from showing nothing to the normal operation.

After say an hour, clicking a button kicks off a whole lot of GETs from the queue which results in the device not responding for a long time (nothing shown in the LCD) and finally an error (E5).

As I don't have any logging more then the CLI, I can only try and deduct what is going on. But it seems the Wakeup Notification is not handled well (except when clicking a button). Perhaps the command is not sent correctly, or Homey does not acknowledge the Notification?

**Comment by WeeJeWel** [comment]
Maybe it's an idea to add a 'online' event to ZwaveDriver, instead of polling. ZwaveDriver itself already receives the event, so it only needs to be passed through.

**Comment by mruiter** [comment]
OpenHab also had these problems . They found out that the danfoss did not get acknoledged on all its z-wave questions to the controller. Therefor it kept repeating this and so draining all its battery power in a day.

I sounds like the exact problem

**Comment by mruiter** [comment]
Just to see a nice battery usage drop see picture
![danny](https://cloud.githubusercontent.com/assets/17739535/20393892/e844969c-acdd-11e6-8186-81a76192a057.JPG)

**Comment by michelderu** [comment]
I've been going through a thread about a driver for SmartThings. There the E5 error was fixed after a while and some help by Danfoss.

It seems the trick there was to send a WAKE_UP_NO_MORE_INFORMATION after the device sent the Wake Up Notification to the controller and all GETs and SETs have been handled.

Pseudo code from https://github.com/richdp/mysmartthings/blob/master/Danfoss%20LC13%20v0.7:

OnWakeUpEvent:
- batteryGet
- thermostatSetpointSet
- thermostatSetpointGet
- wakeUpNoMoreInformation

Could this be it for this device? How could we handle the WAKE_UP_NO_MORE_INFORMATION in the driver?

**Comment by RobinBol** [comment]
@michelderu Thanks for your help! We have looked at it, and think we have fixed it. The fix will come with the next Homey firmware update as it had to be fixed in the core, not in the app(s).

**Comment by michelderu** [comment]
@RobinBol, thanks! I'm very curious to see the next release of the firmware and to test it.

- Can you elaborate (just a bit) about what the fix consists of, so I can understand what's behind it
- Is it necessary to use the pollInterval in the App?
- Can you explain how to call the COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE from the Driver?

**Comment by RobinBol** [comment]
The problem was that not always the WAKEUP_NO_MORE_INFORMATION was send, so overtime the Danfoss started to complain.

Yes that is necessary for now, I am thinking of some function that will only send the SETs/GETs when the devices wakes up.

The following example is taken from Fibaro FGWPE-101, and demonstrates how to access a node and its command classes:

```
Homey.manager('flow').on('action.FGWPE_led_on', (callback, args) => {
	const node = module.exports.nodes[args.device['token']];
	const color = new Buffer([args.color]);
	
	node.instance.CommandClass['COMMAND_CLASS_CONFIGURATION'].CONFIGURATION_SET({
		"Parameter Number": 61,
		"Level": {
			"Size": 1,
			"Default": false
		},
		'Configuration Value': color
	});
	
	callback(null, true);
});
```

**Comment by PandaNL** [comment]
Thank you Athom and michelderu for coming to a solution, will check today and tomorow with 1.0.2 to see if the error stays away, for now it does after the update.

**Comment by michelderu** [comment]
Thank you very much @RobinBol for making the fix available. From what I've been able to see in this short time, it does indeed work with the Devolo (and I guess the Danfoss) device.

Big compliments for acting so quickly and taking the community effort so serious!

Have a great weekend!

**Comment by WeeJeWel** [comment]
Glad to hear its resolved!

**Comment by Rob-Houweling** [comment]
Hi,

This issue still persist with the danfoss thermostats.
Please reopen this issue.
I am experiencing this issue myself and see here for more people:
https://forum.athom.com/discussion/2729/why-is-this-easy-stuff-not-working#latest

**Comment by RobinBol** [comment]
Hi Rob, thanks for reporting your problem. We know the issue still persists and have an issue open to resolve that (https://github.com/athombv/homey/issues/1187). We are working with Danfoss to prevent this error from happening, but will take a while to completely resolve, stay tuned!

Clossing this issue as duplicate of https://github.com/athombv/homey/issues/1187
