### ISSUE TITLE
Push notifications android

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#1087]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**
Receive push notifications on my Android Sony Z5

*Please include detailed steps how we can reproduce the issue*
I have several flows that send me a push message. Since this morning there are not working

**What was the result?**
Not receiving push notification

**What did you expect as result?**
receive push notification

**Any other remarks**
Also test button for the flows not working

**Comment by bvdbos** [comment]
confirmed, also on the forums...

**Comment by jeroenvano** [comment]
I am experiencing the same issue, currently push notifications are not working on all devices.
Running Homey v1.0.1
Cleaned up and removed old phone in https://my.athom.com/#/phones 
New phone was already in the list but after deleting older phones notifications stopped working.

**Comment by WeeJeWel** [comment]
We're working on it!

**Comment by jeroenvollenbrock** [comment]
This issue has been resolved in version 2.3.0 of the App.

**Comment by JPe2** [comment]
@jeroenvollenbrock  sorry there is no installable app for the standard PUSH function, this is the build in PUSH-function that is still not working in Homey V1.0.2. It was ok in the later 0.9.x version.

**Comment by Dijker** [comment]
@JPe2 guess jeroen mentions the updated android app. You should check the My Phones menu to remove old phones and fix the flows to send to the new registered phones after the update. 

Guess almost everyone had a problem due to a bug they fixed in the phone apps.

**Comment by JPe2** [comment]
Thanks @Dijker , but were do I find "**My Phones menu**" or better the **Dutch** version? Is it in Homey or in the Android-App?

**Comment by Dijker** [comment]
On the login menu on your avatar.
![screenshot_20161127-160727](https://cloud.githubusercontent.com/assets/12412734/20649282/2c6ccbe2-b4bc-11e6-97c0-45f5a4c9a1ed.jpg)

**Comment by JPe2** [comment]
Thanks @Dijker, never seen that before, seems a bit hidden for the users of my level (average?).
