### ISSUE TITLE
Adding of Z-Wave Fibaro dimmers fails consistently

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#129]
Have tried to add Fibaro Dimmer 2 multiple times. Although I was able to maybe add one or two, adding more devices fails. Typically, I get this error:
![schermafbeelding 2016-02-11 om 19 09 06](https://cloud.githubusercontent.com/assets/17163901/12989448/f0a825f6-d105-11e5-8a8b-e165bf0f41b6.png)
...and then when it succeeds, I am able to select the Device type. Most of the times, though, I am 'thrown back' to the screen allowing me to add a device. A node is added, but nothing can be done with it.

**Comment by Muyz** [comment]
During interviewing of device 1 of a Dimmer 2, all of a sudden this screen appears. 

![schermafbeelding 2016-02-11 om 22 31 00](https://cloud.githubusercontent.com/assets/17163901/12991368/461bf086-d10f-11e5-8e8d-bb144ccd709b.png)

**Comment by Fire69** [comment]
Same problems here.

**Comment by Muyz** [comment]
And BTW: yes, Homey and the dimmer are close:
![img_1518](https://cloud.githubusercontent.com/assets/17163901/12992158/14238630-d113-11e5-82c6-5eca9c3eb090.JPG)

**Comment by ocatie** [comment]
Known issue with the Fibaro Dimmer 2. Looking into it.

**Comment by ocatie** [comment]
During the interview the endnodes (3.1 and 3.2 in your screenshot) in this multichannel device don't answer a command. The pairing continues after a 30 second timeout. This results in a 1 minute delay overall. The root device is added successful and the dimmer can be used.

For now this is a wont fix because the device doesn't answer a command of a command class it presents as supported. An app will fix this in the future.

**Comment by ocatie** [comment]
The current powerlevel is reported to endnode 1 which fails during the pairing. This results in no powerlevel is reported at the moment.

**Comment by Muyz** [comment]
I don't understand: you say that the root device is added and that the dimmer can be used. This is *not* the case. The dimmer is not added.

**Comment by ocatie** [comment]
Could you post a screenshots what happens after you press the Ok button in the alert box?

I can add the root device and dim a load at the office.

**Comment by Muyz** [comment]
I will try and add the devices later tonight and provide more feedback. More than once I've seen that the next screen that appears is the screen showing devices without any additional message being shown, i.e. the same screen that was shown prior to adding the dimmer.

**Comment by Fire69** [comment]
Same here, the dimmer is not added at all! It fails every time during the interview and no node is added.

**Comment by ocatie** [comment]
I see, the root device (node 3) also fails when you add the device. I can't reproduce the error with all 3 devices failing.

Could you remove the device from the network and then try again after a reboot?

**Comment by Muyz** [comment]
I've done this so many times...obviously.... ;-)

**Comment by ocatie** [comment]
Please try again on 0.8.18.

This is my result.
![screen shot 2016-02-12 at 17 35 43](https://cloud.githubusercontent.com/assets/16609932/13013326/45b3c7c2-d1af-11e5-90c0-97a52040b054.png)
![screen shot 2016-02-12 at 17 37 34](https://cloud.githubusercontent.com/assets/16609932/13013350/67e74b70-d1af-11e5-8dca-4d89e4b6997e.png)
![screen shot 2016-02-12 at 17 37 55](https://cloud.githubusercontent.com/assets/16609932/13013356/6ebd8ca2-d1af-11e5-8713-89d86fe4d2b3.png)

**Comment by athomey** [comment]
Alirght, when is this future app planned? I need to know this, so I know when I can continue my Domotica experiments with Homey. This is a showstopper for using it in any way with S1 and S2 switches, which now isn't possible?

**Comment by athomey** [comment]
Also, this problem of adding it as a non-app generic zwave device, with these errors, seems to trigger a block of regularly removing the device. After which you cannot remove the device, nor the nodes anymore. How do you plan to tackle adding a device as a generic zwave devices as in this thread, while NOT creating a blocked device and ghost nodes?  See details here: https://github.com/athombv/homey/issues/167

**Comment by ocatie** [comment]
Z-Wave apps will be made after the Z-Wave API is finished. Unfortunately I can't put a date on it.

I'm looking into #167, I think the driver crashes somewhere but so far I'm not able to reproduce the error.

**Comment by Muyz** [comment]
Couldn't agree more. This is definitely a showstopper for me as well.

**Comment by athomey** [comment]
@ocatie  You only answer one question I asked. Thx for that! :-)  The question you overlooked is: "How do you plan to tackle adding a device as a generic zwave devices as in this thread, while NOT creating a blocked device and ghost nodes? [thus making it monkey proof, which it is not right now] See details here: #167"

This is a design/architecture question. With good vision, answers, I'll be reassured and will wait till you are ready.  :-)  

Keep up the good work! :+1:

**Comment by ocatie** [comment]
I tend to blame the device for not answering a supported command, it is hard to change the generic template for this device without breaking pairing for other devices. But don't worry, I'm far from done with the dimmer ;)
But for now off to bed ZzZzzz

**Comment by ocatie** [comment]
At the moment I don't think the failed pairing and the crashing driver are related.

**Comment by athomey** [comment]
@ocatie  Appreciate all the hard work, and late hours. Sweet dreams!  I'd appreciate keeping issues OPEN and not CLOSING them if they are clearly not fixed. It gives a wrong impression of amount of open issues, and the impression of where we are at development. What is your vision on this?

**Comment by athomey** [comment]
@Muyz   do you have these issues:   https://github.com/athombv/homey/issues/167  ?  I simply factory reset the Dimmer v2 and then I have ghost devices/nodes, which I never get deleted anymore.  I see a relation with this issue you opened (and Taco closed again)?

**Comment by Muyz** [comment]
Yes, I did see issues as described in [#167](https://github.com/athombv/homey/issues/167). However, something which I do not do, is factory reset the Dimmer v2. If pairing fails, I typically remove the node:

![schermafbeelding 2016-02-12 om 23 57 01](https://cloud.githubusercontent.com/assets/17163901/13022883/6185a6f2-d1e4-11e5-9eeb-c7ca4c2200b9.png)

and then remove the failed node:
![schermafbeelding 2016-02-12 om 23 58 04](https://cloud.githubusercontent.com/assets/17163901/13022906/7eb6e1a0-d1e4-11e5-85a0-c30bf41c2af6.png)

Sometimes this fails and Z-Wave hangs so I have to reboot. 

Before I followed procedure as described above I was also left with ghost devices, leaving me no other option but resetting the Z-Wave network:

![schermafbeelding 2016-02-13 om 00 00 13](https://cloud.githubusercontent.com/assets/17163901/13022967/c8a0d0aa-d1e4-11e5-8e60-88a14d7d2e7a.png)

**Comment by athomey** [comment]
@Muyz thx for details. The factory reset of the Dimmer, I do that because I could not remove it the "normal" way. mmm... You say resetting the Zwave network removes ghost devices? For me this doesn't work, I just tried that.

**Comment by Muyz** [comment]
For me resetting the Z-Wave network worked multiple times in the sense that it removed all devices...which means a lot of work to get all devices paired again...

**Comment by athomey** [comment]
That sounds HORRIBLE, I haven't had that problem (yet). ;-)

**Comment by Muyz** [comment]
If you just tried resetting the Z-Wave network, all your devices should have been removed. Apparently, resetting failed. (BTW: Yes, it is horrible...especially considering I have my Homey for only two days :-P)

**Comment by athomey** [comment]
Wow... Glad it failed then... It should have clearer warnings, mulitple ones.....Or I didn't read all the warnings....

**Comment by ocatie** [comment]
I've closed the issue because the issue about the dimmer is known and a wontfix for now because the device doesn't answer a command it present supported.

Please open a new issue if the reset still fails immediately after a reboot. Otherwise the cause is a crash in the driver I'm already looking for.

**Comment by ocatie** [comment]
Completely fixed in 0.8.19. Sorry it was my fault ;)

**Comment by Fire69** [comment]
Great news!! :+1:

**Comment by Muyz** [comment]
Installed 0.8.20 and issue persists. When I try to add a dimmer, it takes a very long time to interview the dimmer. In the end, it fails with a popup telling that there is another session active. An unknown node is added, which I have to manually remove. Suggest to reopen.

**Comment by Fire69** [comment]
Installed .20 also.
Tried refreshing devices that were not responding.  After the refresh still not responding.
I tried removing some devices I had paired with my precious controller again, that didn't work.
All of a sudden the z-wave page wouldn't load anymore, just saw the little spinning circle...
After a reboot I had the same problems.
Did a reset of my z-wave network.  All my devices seemed gone, but after another reboot, they all came back!

I got a little desperate at that point and did a full reset of my Homey...
Only added 1 device now as a test.  I'll see if that becomes unresponsive again or not...
