### ISSUE TITLE
samsung remote is paired but homey wont send uot signal

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#135]
I have a samsung remote 
Homey reconized the remote but after flow is set up homey wont send a infrared command to television
Homey software  is 0.8.17
this was tested in with the test option in flow

**Comment by filoor** [comment]
Have the same problem

**Comment by Muyz** [comment]
Same here

**Comment by wslybkkr** [comment]
And same here!

**Comment by soler2000** [comment]
same here

**Comment by petergab94** [comment]
same here

**Comment by Jurgen0000** [comment]
Unfortunately same here. Denon amplifier remote is not even recognised.

**Comment by goldenice** [comment]
I'm sorry guys. Apparently sending of IR signals is broken. Will fix this with the introduction of the new pairing wizard. That's probably next update or the one after that.

**Comment by goldenice** [comment]
Should be fixed in 0.8.20.

**Comment by rhannink** [comment]
Hello,
I run firmware version 0.8.29 and it still does not work.
I learned the power button from my Sony remote. When I use this learned button to receive as IF, it works but when I use it as a THEN action, nothing happens.

Gr. Remco

**Comment by maaikekaasenbrood** [comment]
I have the same problem, receiving IR commands seems to work better than giving ir output
[version: 0.8.32]
