### ISSUE TITLE
Can't add/remove Music to playlists and remove queue

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1386]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**

After less than 24h it seems impossible for me to amend any sort of things to the playlists:

- Not possible to add song to playlist
- Not possible to remove song to a playlist
- Not possible to add a song to a "new playlist" (New playlist is created however, song not added)

It is however possible to add a song to the Que with the IOS app beta build 66,

![media add-delete music](https://cloud.githubusercontent.com/assets/17526110/24149361/93fa2842-0e42-11e7-870f-21fe17d28544.JPG)

Just before the log was send, triggered a lot of adding/removing to playlists, log: 34FD21FB3F

**Comment by Arjanvde** [comment]
When adding a song with "Create New Playlist" gives the following error in the console:

![new error](https://cloud.githubusercontent.com/assets/17526110/24149534/28ebfb6a-0e43-11e7-82e4-8bc21f7d7c17.JPG)

**Comment by TheMSB** [comment]
Seems like a potential issue with the frontend you are using, are you using the DesktopClient or a Browser? If so what Browser are you using?

**Comment by Arjanvde** [comment]
@TheMSB, Google Chrome (Version 56.0.2924.87).

Will check this also tonight with the app on my Macbook. If needed I can grant you access to my Homey.

**Comment by Arjanvde** [comment]
To add, I'm possible to add music to the queue once I've searched for a song.

**Comment by TheMSB** [comment]
> To add, I'm possible to add music to the queue once I've searched for a song.

You mean to say that you cannot add any songs?

**Comment by Arjanvde** [comment]
@TheMSB The only thing that is working is adding songs to the queue.

Adding songs to any sort off playlist doesn't work (new and existing playlists). Also removing songs from playlists and the queue doesn't work. If you provide me with your Homey Account I'll add you to my Homey and you can check this yourselves.

This doesn't work with Google Chrome and the Athom app 1.0.1 on mac.

**Comment by chrisboer** [comment]
I can add a new playlist and change the name of the playlist and also add songs to it and remove songs
<img width="1430" alt="afspeellijst" src="https://cloud.githubusercontent.com/assets/23163409/24159579/bb29ff60-0e5f-11e7-9817-55a5b66c8c3e.png">
<img width="1430" alt="afspeellijst_verwijderen" src="https://cloud.githubusercontent.com/assets/23163409/24159581/bc96702c-0e5f-11e7-888a-293b60aac9b9.png">

**Comment by Arjanvde** [comment]
@chrisboer Simple, I can't. Therefore it's up to the Athom Team to fix this.

**Comment by Arjanvde** [comment]
@TheMSB got a second Homey where this isn't working. Neither in Chrome, Neither in the desktop App.

**Comment by TheMSB** [comment]
@Arjanvde To summarise:

- You have two homey devices that are running 1.2.0 RC8
- Both of them encounter the same issue that Sonos playlists are not being synched
- Both of them had Sonos playlist synching working at some earlier point in time.

**Comment by Arjanvde** [comment]
@TheMSB ,

I've  got 2 Homey's running 1.2.0 RC8, and they both have the same issue! It is not a Sonos playlist. but the playlistst which Homey can Create.

**Let me summarise:**

**Problem 1**
I can't add any songs to a playlist (Existing, Favorites or New) which are displayed in the Up Next section, and I can't remove any songs which are displayed on the Up Next Section.  So clearing the up next section is not possible.

**Problem 2**
I can't add a song from the Queue to the up Next section. Also I can't add any songs to a playlist (Existing, Favorites or New) which are displayed in the Queue section.

![music 1](https://cloud.githubusercontent.com/assets/17526110/24192314/c3a9de32-0eee-11e7-9c26-ac87f0e74c31.JPG)

**Problem 2**

I can't remove a song from any playlist (also favorites) or can add them to an Existing, or New playlist

![favorites](https://cloud.githubusercontent.com/assets/17526110/24192591/c6415c8c-0eef-11e7-8bb4-1b82febae1d4.JPG)

The only thing that does work is adding a song to a playlist once I've searched for a song and add it directly to a playlist, all of the above doesn't which makes music very complicated!

![works](https://cloud.githubusercontent.com/assets/17526110/24192724/35029014-0ef0-11e7-8767-923e863cf0e0.JPG)

**Comment by TheMSB** [comment]
@Arjanvde My apologies I got two issues mixed up, I will further investigate this issue and see if I can identify the correct cause.

**Comment by WeeJeWel** [comment]
Thanks, I see the error has been caused by our javascript minifier. This will be resolved in the next version.

**Comment by Arjanvde** [comment]
Thanks for fixing!

**Comment by TheMSB** [comment]
@Arjanvde Can you confirm the issue has been resolved on your end?

**Comment by Arjanvde** [comment]
@TheMSB I haven't seen a new firmware release, so currently it isn't solved.

**Comment by Arjanvde** [comment]
Fixed with RC9
