### ISSUE TITLE
Mutebutton Sonos in media player does not work

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1394]
**What is your Homey version (Settings → System)?**
v1.2.0 rc8

**What did you try to achieve?**
Got a phonecall and wanted to mute Sonos so pressed the mute button but Sonos just continues playing and mute X disappears after a few seconds.

*Please include detailed steps how we can reproduce the issue*
<img width="1428" alt="mutewerktniet" src="https://cloud.githubusercontent.com/assets/23163409/24212969/43aebbd8-0f31-11e7-89ab-1d7431939f0a.png">

**What was the result?**
No music mute

**What did you expect as result?**
To be able to press the mute button and sonos pauses playing

**Any other remarks**
Instead I now pressed the pause play button and that worked ;-)

**Comment by chrisboer** [comment]
Also does not work with 1.2.0 RC9

**Comment by BasKiers** [comment]
Hi,

Could you check which version of the app you are using? There was a bug that when playing from a sonos group only one speaker would be muted. This should be fixed as of version 2.2.1 of the Sonos app.

Regards,
Bas

**Comment by chrisboer** [comment]
Still an issue with Sonos 2.2.2

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24299645/26fe6e64-10aa-11e7-891e-e3b102430335.png)

**Comment by chrisboer** [comment]
In keuken : there is a Sonos Play 5 and Sonos SUB device.

**Comment by chrisboer** [comment]
I found the cause of this problem, if you open de IOS Sonos app you should deselect all speaker groups than it works perfect in "Muziek" but I think it should be desireable to have this possibility also when your Sonos app is running on IOS.

**Comment by chrisboer** [comment]
After update 1.2.0 RC10 mute button works perfect, even when you use Sonos IOS app it detects speakers are not available anymore and put the default speaker back to Homey. 
After you select Sonos on homey again it starts playing media from there again and mutes the Sonos IOS App again. 
Very nice !
