### ISSUE TITLE
homey date stays wrong and no connection to cloud

### ISSUE THREAD

**Issue by mirakels** [athombv/homey#1652]
**What is your Homey version (Settings → System)?**

1.3.0-rc11

**What did you try to achieve?**

reboot and power off/on

*Please include detailed steps how we can reproduce the issue*

Notifications show:

update to 1.3.0-rc9 22 days ago
update to 1.3.0-rc11 about a year ago

**What was the result?**

no change, still no connection to cloud and date is still 2016-05-21T22:56:22.471Z
...

**What did you expect as result?**

a normal functioning homey

**Any other remarks**

I did not actively use home for a few weeks. It was just swotched on and running
Apparently around the upgrade to rc11 things went wrong.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

.When trying this I get a popup window: "certificate is not yet valid"..

Althoug devices seem to function (the temperature sensors do show info), but things are not saved in insight. The template I created just show no graphs anymore

**Comment by jeroenvollenbrock** [comment]
You can use the wifi recovery wizard (turn homey upside down for 10 seconds while it is on) to update to the latest homey firmware, in which this problem has been resolved.

**Comment by mirakels** [comment]
Tried it, but it still fails
I get 'sorry I could not connect to this wifi network'
However when I look at the message log on my dhcp server i see homey received an ip-address.
And because the dhcp server is behind the wifi network it logically means homey must have been connected to the wifi network...

**Comment by mirakels** [comment]
no further advise? I did supply user feedback. but tag is still  'waiting for user feedback' ...

**Comment by jeroenvollenbrock** [comment]
Could you please contact us at support@athom.com and mention GH#1652 for further assistance?
