### ISSUE TITLE
RTS range poor

### ISSUE THREAD

**Issue by edtst** [athombv/homey#177]
I have 3 RTS, mains powered Somfy screens. When Homey is less then a few m away from either of them they work, but more than that and there is no signal. 

My Somfy remote works up to 10-15 m away.

**Comment by Dennishacq** [comment]
Hi edtst,

> This is mainly because Somfy devices use a an frequency that deviates significantly in base frequency from 433.92 which probably causes the loss of range. 
This doesn't mean that Homey (hardware) is incapable of controlling it. Our goal is to support as many devices as possible which means that we have to deal with allot of different radio frequencies and signals. the challenge is to find the optimal radio configuration which gives all the 433Mhz (and 868Mhz) devices the optimal range. This is a continually repeating process which in the end results in the optimal configuration.

**Comment by edtst** [comment]
OK, I hope you will find that config soon, because this is rather dissapointing.

**Comment by Dennishacq** [comment]
We are working on a solution for this problem so it shouldn't be too long before it's fixed.

**Comment by bvdbos** [comment]
"working on" and "not too long" "We are hoping to have it fixed in the next update" means this bug should stay open till the fix is confirmed?

**Comment by freemann** [comment]
+2 for bvdbos.

Its very strange to close issues when the are not really fixed.

**Comment by kingdong78** [comment]
+1 for same problem
I can't include mu its window blinds

**Comment by Jurgen0000** [comment]
@Athom:
Tried the new version of RTS today ... same problem as before.. no way I can pair a RTS screen. All screens are main powered. Placed at different distances.. will try at less than a meter tomorrrow. No issues with any of the remotes from Somfy (even work at almost 80 meter across the street at my neighbours home). All screens are also working with a Homewizard which is even located at a more distant location. Hope you guys can solve this issue.
Version 1.0.6 of Somfy App

**Comment by athom** [comment]
I believe @Jurgen0000 mentioned the wrong guy,
and it's interesting to see there is a cool product picks my fancy login name :smile_cat:

**Comment by Jurgen0000** [comment]
Sorry Athom... seeing more people will receive their Homey from Athom .. your name might popup more often ..

**Comment by ReinierH** [comment]
After several tests we now can confirm that we've solved the range problems. The fix will probably be patched in 0.8.19.

**Comment by edtst** [comment]
It usd to work fine but now the range is not as good as it was after this fix. Homey now misses my furthest shutter quite often. It is at 8 m from Homey with 2 doors between it. This used to work.

**Comment by ReinierH** [comment]
@edtst 
That's interesting, does powercycling your Homey fix it or does it stay the same?

**Comment by edtst** [comment]
It varies. Sometimes it's a little better. It used to be really good at one point after this was fixed.
