### ISSUE TITLE
Motion and sabotage alarm stay on with firbaro Motion (Zwave plus)

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#1785]
**What is your Homey version (Settings → System)?**

1.5 rc9

Motion and sabotage-alarm are on and never go off after reboot. Also waking up the device wont help.

On Slack it seemed there are more people having this issue. Since the Motion alarm stays on it also does not detect any Motion again (flows are not triggered)

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by robiebab** [comment]
Having the same issues as jeroen. This issue occured Since 1.4.0 see last ticket

**Comment by philsniff** [comment]
i have the same issue but for month now. evers reboot or firmware upgrade the motion alarm stays.
but i can trible click the b-button and from then it works like it should.
untill the next reboot or firmwareupdate :-)

**Comment by corvdniet** [comment]
Have you tried a reboot and then wait for one hour (don't triple click the b-button in the meantime)?

**Comment by philsniff** [comment]
no i don't wait so long 'cause of it shoould work in my hallway and i reboot/upgrade only in the evening when i am at home and at this time the hallway lights should work immediately. so i didn't wait too long in the past.

i will check next time

**Comment by MbenzNo** [comment]
Same problem with one of four sensors in my system. One of the sensors have constantly motion alarm and is constantly triggering flow associated with it. No tamper alarm.

**Comment by corvdniet** [comment]
Yesterday (automatic) update to Fibaro 1.5.9. Motion kept on :-(

**Comment by WeeJeWel** [comment]
I have tried to reproduce the issue but the Fibaro Motion Sensor (FGMS-001-PLUS) worked correct here. Motion was detected, and again went off, lux, battery and temperature were reported, and the sabotage alarm worked as well.

Am I correct to assume that the syncing only happens after a reboot?

**Comment by robiebab** [comment]
That is correct, it only happens after a reboot. Most off the time it happens within 30-60min.

Verstuurd vanaf mijn iPhone

**Comment by jeroenbos22** [comment]
@weejewel try for a longer period. Here Some days its good and Some days it stays on for a couple of hours - days

**Comment by philsniff** [comment]
i just rebootet yesterday because of another problemn (fibaro door sensor first gen suddently shows 'invalid_commandclass_commandclassnotification' sincs fibaro-update) and my montionsensor (fibaro) stays on with tamperalarm!

no reboot, PTP or wakeup of the device can stop the tamperalarm!
when i had this problem befor, i just wokeup the device again, and it went off. (mostly after a reboot the alarm was staying...)

but this is now new: i can't stop it anymore!

**Comment by weerderhof** [comment]
I just have the same problem, is it a problem of the app or the Homey?

**Comment by ivleth** [comment]
I have this as well on after rebooting, sometimes also on the door-window sensors, https://www.fibaro.com/en/products/door-window-sensor/

**Comment by corvdniet** [comment]
Imho this bug isn't fixed yet in 1.5.4 (exp. channel)

**Comment by philsniff** [comment]
Yes my motion sensor still won‘t stop the tamper Alarm After the Update to 1.5.4!
No ptp, No reboot and No manual wakeup of the sensor near homey can stop this damn blinking

**Comment by corvdniet** [comment]
Taking out the battery for 20 seconds is a workaround for me. Have to do that every PTP of restart of Homey 👎

**Comment by philsniff** [comment]
ok, will try it. but i took the battery out and in, just i didn't let it out for some seconds.

so i will tray with 20 seconds...

**Comment by corvdniet** [comment]
There are rumours that this will be fixed in 1.5.5. Can anyone confirm that that's the intention?

**Comment by WeeJeWel** [comment]
1.5.6 will include some Z-Wave fixes

**Comment by philsniff** [comment]
would be great ;-)

**Comment by SkorpionNL** [comment]
Good news. I mostly experience this issue with Neo Coolcam door sensors reporting wrong statuses over and over.

**Comment by jeroenbos22** [comment]
Dont cheer too early @SkorpionNL , think its just luck because here it was on the Fibaro all the time and now it sometimes shows on the Neo. It tends to jump to other devices (from multiple apps) on reboot / restart.

**Comment by WeeJeWel** [comment]
This should be fixed in 1.5.6-rc.4. Please let me know if the problem persists.

**Comment by philsniff** [comment]
when 1.5.6 is relesed in experimental channel i will let you know ;-)

**Comment by philsniff** [comment]
Sadly the tamper alarm still blinking on firmware 1.5.6-rc6
I also had to trible press the b button to wake up the motion sensor manually because one Hour after update to the latest firmeware the motion alarm won't stop blinking. After wäre up the motion alarm wen off but the tamper alarm won't go down on its knees. 

So all exactly like before the update

**Comment by jghaanstra** [comment]
I have the exact seem experience as @philsniff.

**Comment by corvdniet** [comment]
+1

**Comment by Inversion-NL** [comment]
I have an Fibaro Smoke sensor (v1) which is triggering tamper alarm all the time.
The other Fibaro Smoke sensors I have (all v1) don't have the issue.

**Comment by corvdniet** [comment]
Not solved in 1.5.6-rc7 :-(

**Comment by philsniff** [comment]
right: tamper alarm still triggering tamper alarm with 1,5,6-rc7

**Comment by Inversion-NL** [comment]
Same here.

**Comment by Fiek1** [comment]
same here

**Comment by LeCauf** [comment]
For me the motion alert stays on and other data like battery status are not always visible. Removing the battery for about half a minute does the trick.

**Comment by philsniff** [comment]
The battery status is fake. It is just refreshed when removing battery. But it is fake and will be „-„ after some time again.

**Comment by corvdniet** [comment]
Seems solved in 1.5.6-rc8. Did not expect that after consulting the firmware description. Anyone experiencing the same?

**Comment by jghaanstra** [comment]
Not solved for me on RC8. Tamper alarm of my Fibaro sensor still activates out of the blue some time after a reboot and then never cancels again.

**Comment by philsniff** [comment]
Not solved with rc8 :-(

**Comment by jeroenbos22** [comment]
Agree, it now works most of the time here but definitely not always. Certainly not fixed in rc8

**Comment by Inversion-NL** [comment]
Same for me: 1 of 5 Fibaro smoke keeps triggering tamper alarm.

**Comment by JesperJanssen** [comment]
I have the same problem thw motion alarm on my fibaro motion sensor z-wave plus. The motion alarm was always turned on when I checked the motion sensor in the app. As a result my motion activated flow where not triggering correctly.

Today I saw that my motion alarm was not working anymore (LED eye was turning on anymore). Apparently the battery was empty but the Homey app is still showing the Fibaro Motion sensor with motion alarm turned on. So maybe this is related to the problem and you can use this info to solve it.

**Comment by corvdniet** [comment]
Guess I was lucky 5 days ago. Did another restart and motion kept on ... not solved with rc8

**Comment by WeeJeWel** [comment]
Could it be that the sensor reports the 'Alarm off' status during Homey's reboot? Of course, when Homey is rebooting, it does not listen for incoming changes.

**Comment by jghaanstra** [comment]
@WeeJeWel  That is not the case, at least not for me. After a Homey reboot and/or waking up the device my sabotage alarm is cancelled. But sometime later without any reason all of a sudden the sabotage alarm is triggered again and than always stays on until a new Homey reboot or wake up of the device.

**Comment by WeeJeWel** [comment]
When it triggers again, do you see a message coming from the device in the Z-Wave log?

**Comment by jghaanstra** [comment]
I'll see if I can catch it but most of the times it's hours after a reboot when the sabotage alarm is triggered out of the blue. As you can understand I'm not gonna monitor the zwave log for hours. But I'll leave it open and see if I can filter it once it happens.

**Comment by WeeJeWel** [comment]
That would help a lot, thanks!

**Comment by WeeJeWel** [comment]
I have published a new version of the Fibaro app (v1.5.15, beta) which might solve this issue. Could you guys test it?

**Comment by jghaanstra** [comment]
I was waiting for the tamper alarm to go off again and catch it in the log. Obviously now that I'm monitoring it it doesnt happen in the first couple of hours of the reboot and I got tired of waiting. I just installed the beta and will see if that gets rid of the issue permantly.

**Comment by cbho** [comment]
Installed the new version of the app (running 1.5.6-rc8) - and re-included a Motion Sensor - and stuff seemed to work.

Changed sensitivity - and the sensor just kept reporting motion was detected:
Node[141]: [COMMAND_CLASS_NOTIFICATION] {"V1 Alarm Type (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Type":0,"V1 Alarm Level (Raw)":{"type":"Buffer","data":[0]},"V1 Alarm Level":0,"Reserved (Raw)":{"type":"Buffer","data":[0]},"Notification Status (Raw)":{"type":"Buffer","data":[255]},"Notification Status":"On","Notification Type (Raw)":{"type":"Buffer","data":[7]},"Notification Type":"Home Security","Event (Raw)":{"type":"Buffer","data":[8]},"Event":8,"Properties1 (Raw)":{"type":"Buffer","data":[0]},"Properties1":{"Event Parameters Length":0,"Sequence":false},"Event (Parsed)":"Motion Detection, Unknown Location"}

Removed and re-included the sensor and has left settings untouched - and at present it works as expected.

Could it be something related to the transfer of new settings to the sensor?

A few months ago (can't remember exactly which versions of firmware and app), I had absolutely no problems making direct associations from the same sensor to other devices, but now this is absolutely not possible - hence the thought, that a bug could have found it's way to the process of transferring data to the device...???

**Comment by cbho** [comment]
@jghaanstra: Have you tried to leave the log running on developer.athom.com and then type the node-id in brackets in the line below ("Filter...") (something like [143] or whatever the node-id is)?
Will leave you with significantly fewer lines to go through :-)

**Comment by jghaanstra** [comment]
@cbho I'm aware of the filter function but since the actual issue (alarm not cancelling) did not occur during the time I monitored it there wont be much interesting to see other than succesfull reports.

Your findings about the settings might be of interest though. Did you wake up the sensor manually when you initially changed the sensitivity?

**Comment by cbho** [comment]
@jghaanstra: just mentioned it, as I'm rather good at missing obvious things myself sometimes ;-)

Yes, woke up the device manually.
Almost made it a SOP to manually force updating several times (while checking the log to see when there's definitely not new info transferred from Homey to the device) almost everytime I'm changing settings to be certain something is not stock in the queue somewhere when evaluating the consequences of the changes.

**Comment by jghaanstra** [comment]
It's not fixed with the Fibaro v1.5.15 beta app.

Last thing I did before powering down my laptop was look at the sensor status in the web interface. It had not updated the battery and the tamper alarm (showing dashes) in the mobile card yet after I had updated the app to the beta this afternoon. While I'm brushing my teeth I get a notification on my phone that the tamper alarm has triggered again. Looking at the card the battery status has updated and the tamper alarm is on. After that it wont cancel anymore without cancelling it manually (waking up device or triggering tamper alarm manually).

**Comment by ivoterhorst** [comment]
My Everspring motion sensor has a similar issue with the motion alarm turning on and not cancelling anymore (or it seems to cancel sometimes, at random, after a very long time). Since it's a different brand, I suppose this issue is not Fibaro specific? 

I'll see if I can catch some logging.

**Comment by ivoterhorst** [comment]
See below the z-wave log of the motion sensor (node[19]) just before the sensor stays 'triggered'.
I do notice that it reports value 0 (off) and 255 (on) alternating. The last two log entries seem to be switched: first it reports off (at 2018-02-02T13:09:09.715Z), then on (2018-02-02T13:11:12.899Z). 

Triggering the tamper switch / removing and replacing the batteries at the location where it's mounted to the wall (outside) doesn't result in a new log entry. If I remove it from the wall and move it indoors, closer to Homey, I do see new log entries appearing (reporting on and off in the right order again). Somehow it seems to be out of range, even though I have 2 fibaro devices (a switch and a 'tussenstekker') very close to it. It also used to work fine for years at the same location, so I suspect that routing was never a problem. My network didn't change for a long time, so that should also be ruled out as a root cause.

Hope this helps a bit.

Time | Entry
-- | --
2018-02-02T13:06:20.306Z | Node[19]: [COMMAND_CLASS_ALARM] {"Alarm Type (Raw)":{"type":"Buffer","data":[1]},"Alarm Type":1,"Alarm Level (Raw)":{"type":"Buffer","data":[17]},"Alarm Level":17}
2018-02-02T13:06:27.073Z | Node[19]: Marked as online
2018-02-02T13:06:27.074Z | Node[19]: Received application update: 0x20013070847286858071
2018-02-02T13:06:30.574Z | Node[19]: [COMMAND_CLASS_WAKE_UP] [WAKE_UP_NO_MORE_INFORMATION] {"type":"Buffer","data":[]}
2018-02-02T13:06:30.574Z | Node[19]: sendData to COMMAND_CLASS_WAKE_UP, params 0x08
2018-02-02T13:06:30.627Z | Node[19]: Marked as offline
2018-02-02T13:07:28.841Z | Node[19]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
2018-02-02T13:07:28.842Z | Node[19]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
2018-02-02T13:07:32.907Z | Node[19]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100
2018-02-02T13:07:32.907Z | Node[19]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}
2018-02-02T13:09:04.900Z | Node[19]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
2018-02-02T13:09:04.900Z | Node[19]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}
2018-02-02T13:09:09.488Z | Node[19]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100
2018-02-02T13:09:09.488Z | Node[19]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}
2018-02-02T13:09:09.715Z | Node[19]: Received application command for COMMAND_CLASS_BASIC, data: 0x0100
2018-02-02T13:09:09.715Z | Node[19]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[0]},"Value":0}
2018-02-02T13:11:12.899Z | Node[19]: Received application command for COMMAND_CLASS_BASIC, data: 0x01ff
2018-02-02T13:11:12.900Z | Node[19]: [COMMAND_CLASS_BASIC] {"Value (Raw)":{"type":"Buffer","data":[255]},"Value":255}

**Comment by corvdniet** [comment]
Don't think this issue is solved in 1.5.6.rc11

**Comment by Inversion-NL** [comment]
For me it isn't.
I now have two Fibaro Smoke sensors which report tamper alarm...

**Comment by pakacom** [comment]
My Philips motion sensors has a similar issue.
Motion detection turns on and never go off.
The motion sensoren are directly connected to the Homey through the app Philips Hue ZigBee Version 1.3.0
My firmware Version is 1.5.6-rc13 also i had the same issue on rc11.
for this firmwares it has always worked well.

Log number : 6AB1D08ADC

**Comment by corvdniet** [comment]
Did an update to 1.5.6-rc13 and my Fibaro sensor started OK!

**Comment by philsniff** [comment]
i have to trible click my fibaro motion sensor to see if the tamper alarm still stays armed...

**Comment by ivoterhorst** [comment]
Since the update to 1.5.6-rc.13 it seems to be working OK again

**Comment by ivleth** [comment]
Since rc13, motion is not detected at all anymore on any Fibaro motion sensor, only lux. :-((

**Comment by philsniff** [comment]
My tamper alarm is still blinking after new wakeup of the Fibaro motion sensor. Perhaps i Must deleted and readd it but i don‘t want to. It works and the tamper alarm can blink till the end of the world if it wants to.

**Comment by Inversion-NL** [comment]
I still have three devices which report a tamper alarm.
Two Fibaro smoke sensors (v1)
And one Philio motion sensor who keeps reporting motion...

**Comment by jghaanstra** [comment]
Just chipping in here, this issue is not fixed in 1.5.6 final. I have updated this evening to the final release and what I just now witnessed is the following. Both motion and tamper alarm of my Fibaro sensor triggered out of the blue at the same time. Motion did not cancel again by itself but by triggering the motion alarm with actual movement it was eventually cancelled. Tamper alarm is still on though (I can probably cancel that as well by shaking the sensor but it's out of reach). Point is, they are still triggering out of the blue.

**Comment by corvdniet** [comment]
Since 1.5.6 final the motion keeps on. %$#@^$%# ... , so not solved (again)

**Comment by bvdbos** [comment]
Is the sensor still reporting tamper-alarms or did it stop reporting and Homey didn't register it? What happens if you wake up the sensor manually or (liek @jghaanstra says) force a tamper-alarm? If have one on my kitchen-closet. just opening and closing a closet triggers the alarm.... Like stated on the slack : _The off signal probably got lost somewhere in outer space_

**Comment by corvdniet** [comment]
Yesterday I updated to 1.5.6 final. After the update motion kept on. I did a restart of Homey and motion was off. Today all of a sudden motion was on (not sure about tamper). I just did a restart and motion and tamper are off. Manual motion or tamper triggers work like expected. My conclusion: not stable. Maybe missing off signals could be the cause (like @jghaanstra says). Not sure

**Comment by cjvs** [comment]
On 1.5.6 final an experiencing similar issues as above. Either motion or tamper alarm remains on (or both). Had to pull the battery for a minute to resolve the issue. Pulling the battery works on both z-wave plus sensors I have. Does not survive a reboot.
