### ISSUE TITLE
Flow is not triggering on sunset ends or sunrise starts

### ISSUE THREAD

**Issue by njreus** [athombv/homey#182]
I have a flow that should trigger on sunset ends but unfortunately it doesn't. It does trigger (i.e., the light will turn on) when I make it trigger on a certain time. The same is true for a flow that should trigger on sunrise starts. My location is set to be detected automatically. 
![homey_flow sunset ends](https://cloud.githubusercontent.com/assets/17208591/13030184/6a74f17e-d2a1-11e5-9519-6b452433e598.jpg)
![homey_flow sunrise starts](https://cloud.githubusercontent.com/assets/17208591/13030185/711042b8-d2a1-11e5-8ebf-63ba796de712.jpg)

**Comment by pkonings** [comment]
If you "My location is set to be detected automatically." looks like mine, it could be a problem. Setting it to manually solved also the one hour problem for me.

![image](https://cloud.githubusercontent.com/assets/10164680/13033227/0fe44f70-d30f-11e5-9284-c82634be602d.png)

**Comment by Dijker** [comment]
Testing the trigger will be easier when you "Log" ... so created 4 workflows: (Sunrise/set Start/end) with a pust notification... 
Testing results in time reported 21:23 (every time I tried ;-) )

![image](https://cloud.githubusercontent.com/assets/12412734/13040636/fa1b7e48-d3ae-11e5-9c74-7d977d4634f3.png)

![image](https://cloud.githubusercontent.com/assets/12412734/13040632/f094e3fa-d3ae-11e5-8cae-767fbece1933.png)

Will see result this evening! 
Regards, Geurt

**Comment by WeeJeWel** [comment]
Is your Homey time correct? Settings -> System -> Stuff for geeks -> date

**Comment by freemann** [comment]
The time should not matter, because the Flow exists and if homey is X hours offtime, the flow should eventually trigger.

**Comment by pkonings** [comment]
Please consider permanent (system) time on front screen. Something like this:

![image](https://cloud.githubusercontent.com/assets/10164680/13051391/54a7b2ba-d3f9-11e5-9dc7-d0b4832f1499.png)

**Comment by freemann** [comment]
@pkonings;
+1

**Comment by domey** [comment]
@pkonings 
+1

**Comment by njreus** [comment]
@WeeJeWel, the time is one hour behind. Both when I try it with automatic detection of the location and by manual selection. I will wait for another sunrise and sunset tomorrow. Nonetheless, the last 2 days I have waited several hours after sunrise and sunset to see if the flow would trigger, but it didn't. So I am not confident that the wrong time of Homey is the ultimate culprit.

**Comment by Dijker** [comment]
Same her, last day not much time to play, so no reboot's done. Got not one push notification from Homey about Sunrise/Set start/end.  
Date/time, timezone, and location looks good. 
Running 0.8.17

**Comment by njreus** [comment]
@WeeJeWel I have observed the flow of sunrise and sunset the last couple of days but the flows do not seem to trigger. I do not have an Android phone so I am not able to receive push notifications and cannot test that (which probably would be the easiest way). In my observations, the light doest switch on and off based on a trigger of a certain time but it does not switch on/off based on a trigger of sunset or sunrise.

**Comment by matjaz** [comment]
maybe it's a timezone issue? try "ok homey, what's the time?" #169

**Comment by njreus** [comment]
Interestingly, when I ask homey the time, it gives the correct time. When I look at the time in the Stuff for Geeks section in Homey's software, the time is one hour behind.

**Comment by matjaz** [comment]
That's expected. in geek section time is in UTC.

**Comment by MdeRhoter** [comment]
Looks like it's still not working in 0.8.20

**Comment by WeeJeWel** [comment]
Fixed in 0.8.23 (finally)

**Comment by Arjanvde** [comment]
Time for all events, Sunrise Starts/Ends, Sunset Starts/Ends stays 21:23, so unfortunately not fixed.

**Comment by WeeJeWel** [comment]
@Arjanvde how do you know? And what version are you on?

**Comment by Arjanvde** [comment]
@WeeJeWel 0.8.24, did a test where I drag the time from sunset/sunrise to a slack notification and all times came back at 21:23.

**Comment by WeeJeWel** [comment]
After you pressed 'test'?

**Comment by Arjanvde** [comment]
Yes!

**Comment by WeeJeWel** [comment]
Pressing `Test` ignores the trigger and fills arbritary values for tokens ;)

**Comment by Arjanvde** [comment]
@WeeJeWel, Would the correct time be displayed in a Slack Message as soon sunset is going to start?

**Comment by WeeJeWel** [comment]
Yes, that should happen

**Comment by Arjanvde** [comment]
Made a test flow, will revert if the flow did run at sunset (18:46 in Utrecht tonight).

Thanks so far.

**Comment by Arjanvde** [comment]
Lights did trigger on sunset start!

When the test button is pressed in the future, will the corresponding sunset/sunrise time be displayed?

**Comment by WeeJeWel** [comment]
Great!

And no, the Test button will get a dialog where you can fill in your test
tokens instead.

**Comment by Dijker** [comment]
Looks good, 
Also two flows triggered here this sunset, 
( See at the [Forum ](https://forum.athom.com/discussion/comment/14300/#Comment_14300) )
Will report tomorrow morning if both sunrise events triggered....

**Comment by Dijker** [comment]
@WeeJeWel , 
This morning no triggers from sunrise start/end. (@ Utrecht)
I Also haven't seen the dialog if I pressed Test ;-(   all Test where here reported as 21:23.
Running 0.8.24 since yesterday but the flows (all) where created before. Yesterday  I was pleasantly surprised it worked without any change beside updating to .24 

I Removed the Trigger card and re-added it, saved the flow, but still no Dialog at Test,

I use still the flows like in in my post [3rd from top] (https://github.com/athombv/homey/issues/182#issuecomment-184073120 ) with a Send PushNotify but I changed after a Re-set of Homey in my first week back to English to stay there until it is more stable.

Tried to verify location but I also have te problem #348 so I cant verify at this moment.

**Comment by Arjanvde** [comment]
Having the same issue as Dijker, Sunrise didn't trigger a flow.

**Comment by Arjanvde** [comment]
Sunrise ends/ Sunset Starts didn't start this evening, anybody else having the same issue?

**Comment by Dijker** [comment]
@Arjanvde 
I didn't expect a Sunrise this evening ;-)
But both my Sunset start and Sunset end triggered again this evening! I keep the push notification flows to log if it works!

**Comment by Arjanvde** [comment]
@Dijker I did expect a Sunrise end this evening. I got all 4 possibilities timed with with an action on Slack. None of them have worked since yesterday evening.

**Comment by Arjanvde** [comment]
Thinking about it, tried to check my location yesterday evening and switched it to manual and back and it "could" be lost since the maps is not displayed (#348) and Homey doesn't know my location anymore.

Could this be the issue @WeeJeWel?

**Comment by Dijker** [comment]
@Arjanvde 
Maybe that we expect different definitions of the four triggers. I expect the END of the event a couple of minutes after the start.  I also didn't know how many minutes exact between, but they are very close here. (@Utrecht )

Like yesterday (Sunset Start 18h43 - End .46 ) and today  .45 - .48 

[https://forum.athom.com/discussion/comment/14300/#Comment_14300](https://forum.athom.com/discussion/comment/14300/#Comment_14300)

**Comment by Arjanvde** [comment]
@Dijker I exactly have the same expectation as you do, but it doesn't work anymore, none of the flow do report a time. I think my location has been lost by Homey and it doesn't know where i'm currently are (Maarssen), we can't set our location anymore and i did tried to check my location. The Sunset Start trigger worked yesterday, it didn't work today.

**Comment by CootNL** [comment]
+1

**Comment by WeeJeWel** [comment]
Confirmed. Back to square 1.. :)

**Comment by WeeJeWel** [comment]
Fixed in 0.8.25 (I hope.). Did a complete rewrite, now it really should be rock solid.

**Comment by MdeRhoter** [comment]
Good to hear! Out of interest, what caused it to work for a little while after the release of 0.8.24?

**Comment by WeeJeWel** [comment]
No idea what was broken, that was the problem in the first place. I just rewrote it using the Cron API, which is a lot more solid. :-)

**Comment by Dijker** [comment]
Updated to 0.8.27 just in time: first two triggers worked!
C U tomorrow Morning ;-) 

![image](https://cloud.githubusercontent.com/assets/12412734/14216015/c2cda4fe-f846-11e5-89b6-82e05139a3cb.png)

**Comment by Arjanvde** [comment]
Well hate to tell the news, Sunrise (on/off) still doesn't work. Sunset (on/off) did work on Saturday evening but didn't work Yesterday --> Sunday.

My test flows are simple, send a push notification to Slack.

**Comment by bvdbos** [comment]
Sunset did work for me both saturday and sunday, sunrise didn't work...

>

**Comment by MdeRhoter** [comment]
Same here, even with the new Better Logic app Sunrise still doesn't trigger anything. Just to be sure I'll create a new variable and see what happens. Sunset seems okay.

**Comment by WeeJeWel** [comment]
How is Better Logic related to sunset? :)

**Comment by matjaz** [comment]
breaking change from #developers slack...

For me also just first sunset and sunrise after update to .27 worked. :(
Did make some restarts after that.

**Comment by WeeJeWel** [comment]
So the first time sunset/sunrise triggers, the day after not?

**Comment by Arjanvde** [comment]
In my case, Sunrise never worked, Sunset (on/off) only worked on Saturday evening.

**Comment by matjaz** [comment]
@WeeJeWel yes. after update to .27 all 4 triggers worked only once.

**Comment by MdeRhoter** [comment]
@WeeJeWel - I use trigger flows to set variables and action flows to execute when variables have changed. So when Better Logic stopped working, most of my flows stopped working as well. Including the sunrise/sunset ones.

Sunset works fine, sunrise doesn't.

**Comment by MdeRhoter** [comment]
Now both sunset and sunrise have stopped triggering flows.

**Comment by Arjanvde** [comment]
Sunset (on/off) worked yesterday evening.

**Comment by CootNL** [comment]
This evening sunset start is not working.yesterday and the day before it was working

**Comment by rikpost** [comment]
Did something changed in 0.8.29?
Last 2 evenings the sunset did trigger a flow (send IFTTT e-mail notification). 
I almost can't wait another 24 hours to see if we have 3 out of 3.

**Comment by matjaz** [comment]
So yesterday first day after upgrade to .29 all 4 triggers triggered. Today none of them did. :(

**Comment by markaswift** [comment]
Not working here either.

**Comment by antigreja** [comment]
I have also created some testflows which trigger a lamp at Sunrise/sunset but they never worked once. Any clue as when this issue will be tackled? 

And why are there specific cards for when eg Sunrise Starts and when Sunrise Ends? To me this would only complicate things even more, one Sunrise and Sunset card (like eg in Homewizard) should be ok. 

Also +1 for the idear to have the time and current Sunrise/Sunset times somewhere on the homescreen or settings screen to check it (btw on my settings screen the time is now 2 hours off but when asked the time Homey tells it correctly?!?).

**Comment by bvdbos** [comment]
Sunrise/Sunset runs perfectly for a while after you restart Homey. At some
point however polling-requests to get the time seem to crash (also
Thermosmart suffers from this).

>

**Comment by CootNL** [comment]
Yes after a restart the Sunrise/Sunset is working. The second day after the restart it is not working any more.Is there a way to restart automatically Homey?

**Comment by antigreja** [comment]
I restarted Homey yesterday and sunset worked yesterday evening, but the sunrise trigger this morning not. So it is not workable (a daily restart of Homey seems a bit rough to tackle this simple issue) and hope this is resolved soon.

**Comment by edtst** [comment]
When I reboot Homey, sunset ALWAYS triggers on the correct time once in a flow. After that it never triggers again. I tried both manual location and automatic.

**Comment by MdeRhoter** [comment]
On 0.8.30, sunset worked once (on April 15), sunrise never worked. I'm guessing nothing much changed in the relevant code from .29 to .30?

**Comment by mruiter** [comment]
Is there every going to be a sollution for this bug. Is has been for months now that this basic feature does not work.

**Comment by MdeRhoter** [comment]
0.8.31! Has to be. 0.8.30 was a big step with the new node version, so .31 will be where the rest gets fixed.

Until then, IFTTT does a decent sunrise/sunset trigger.

**Comment by MdeRhoter** [comment]
0.8.32 triggered sunset last night, but no sunrise this morning.

**Comment by daneedk** [comment]
Same here, did get sunset start and sunset end yesterday, no sunrise start nor end.

**Comment by matjaz** [comment]
Same here. it looks like the first time after upgrade.

**Comment by mruiter** [comment]
No sundown yesterday again. looks like broke again in .32

**Comment by mruiter** [comment]
Hey is was opened and closed again without any notice. Is it fixed. More then 10 people have confirmed the problem on the forum.

**Comment by mruiter** [comment]
Ok. Yesterday sundown worked again. Except Sunrise did not work this morning.

**Comment by Dijker** [comment]
Same here 0.8.32, Manual Location (without modifying, it was correct), 
SunSet both triggered, but cant remember any Sunrise Trigger ever happened.

**Comment by daneedk** [comment]
0.8.32
Sunset start and Sunset end on April 28 worked, no Sunrise start nor Sunrise end on April 29.

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.33

**Comment by daneedk** [comment]
Great! Bring it on! :)

**Comment by freemann** [comment]
Exiting!! Will that be a experimental or "stable" release?

**Comment by WeeJeWel** [comment]
Every stable release will have to pass experimental first anyway :)

**Comment by freemann** [comment]
:( 

Next question:
When to expect the next stable release and which release will it be?

**Comment by thezahir1** [comment]
What version number is the next stable release going to be, @Weejewel? And about when?

**Comment by WeeJeWel** [comment]
It's released when it's released :)

**Comment by thezahir1** [comment]
A bit more clearness would be appreciated...

**Comment by WeeJeWel** [comment]
I can't promise when things are stable. That's the whole point of the experimental channel: see what happens.

**Comment by thezahir1** [comment]
That wasn't really my question @WeeJeWel . My (i think also @freemann 's question was: which version will be the next in line to be released as stable version? Will this be 0.8.30 or a later version?
And when is the next stable version planned to be pushed to our Homeys in the field?

**Comment by RoadXY** [comment]
I guess that depends on how stable the next release is.
And that is yet unknown

**Comment by antigreja** [comment]
@WeeJeWel Would it be possible as requested on the forum to display the sunrise/sunset times of the current day? I see there is now an extra entry with the 'Date human' which displays the correct time. Perhaps just below that entry?

**Comment by freemann** [comment]
@RoadXY
Emile mentioned that a Stable first need to go through the Experimental channel.
So its not the case of the next FW is stable enough, its a decision to mark a old Experimental to Stable.

Back on topic;
Displaying Sun info is +1 ! 
It will give a user very useful information about how late a flow will trigger. If that time is not the time a user wants it to trigger, then he can decide to make a own/different flow.

**Comment by Arjanvde** [comment]
Note to users using sunset/sunrise. Please check your flows as the trigger cards have changed!

**Comment by Dijker** [comment]
Thanks @Arjanvde 
Today for me the first time both  two triggers in a row functioned! 
@0.8.34
Looks Promising ....

**Comment by matjaz** [comment]
for me .34 fixed this issue. triggered sunrise/set for 3 days in a row.
