### ISSUE TITLE
Homey offline once a month

### ISSUE THREAD

**Issue by MarcelS1988** [athombv/homey#1944]
**Metadata**

* **Homey Version**: 1.5.4
* **Homey Log Code**: DBD652A9EE

**What did you try to achieve?**
Homey lost his connection once a month.
Last dates it was happend: 5 sep 2017, 12 sep 2017 and 6 nov 2017
Also if you ask something to homey he said, ''kan de server niet bereiken''.

I have also Toon, and he has Always his connection.
Also no other wifi devices has any problems.

To get homey back online i have to restart it.
(Put the kabel off homey)

**What did you expect as result?**
Homey not loss his connection.

**Comment by MarcelS1988** [comment]
@jeroenvollenbrock also I see now the firmware verion of the device are gone, battery status is not available more(this is I get back to the most device to do once a wake up only the fibaro smoke sensor was this not working for).I have tried to re-add 1 device to see if the firmware version is there and the firmware version is back now. So this looks also a bug. It is for all device's fibaro, philio, neo coolcam. Battery device but also power devices.

**Comment by jeroenvollenbrock** [comment]
Should be resolved in 1.5.6-rc.13, can you confirm this?

**Comment by MarcelS1988** [comment]
@jeroenvollenbrock homey last crash was for me on 14 November. So this looks good.. .
The firmware version of the device are still not available. Do you know this already or should I make a new issue?

**Comment by jeroenvollenbrock** [comment]
Hi @MarcelS1988, Could you please create a new issue for this if it persists after re-pairing and re-testing the device?
