### ISSUE TITLE
Weather sensor (433Mhz) not showing up anymore after update to 1.5.6-rc6

### ISSUE THREAD

**Issue by epjjansen** [athombv/homey#2075]
**Metadata**

* **Homey Version**: 1.5.6-rc.6
* **Homey Log Code**:  A581BD423C
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**Wireless Weather Sensors
* **Homey App Version**:v1.2.1
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Alecto WS-1200

**What did you try to achieve?**
Reading temperature and rainfall from Alecto WS-1200 sensor

**What did you expect as result?**
Temperature and rainfall shown in Homey

**What was the result?**
Sensor is not visible in Homey anymore, I have a second weathersensor, the WS-1100 which is presented in Homey

**Any other remarks**
I wanted to send the .json files to the developer of the Wireless Weather Sensors app. The developer wanted some more detailed information. The same night the 1.5.6-rc.6 came out and was installed. Afterwards, the WS-1200 was not picked up anymore by the 433Mhz antennas

**Comment by Maxwell70** [comment]
I agree! Homey no longer see the sensor THGN132N after the last firmware update.

**Comment by nlrb** [comment]
Same here. On rc.6 I could e.g. not receive Oregon Scientific 2.2 sensors anymore and some Oregon Scientific 3.0 sensors. With rc.7 it is worse and I cannot receive any Oregon Scientific signal anymore.

**Comment by Maxwell70** [comment]
On rc.6 and on rc.7 I cannot receive signal from Oregon Scientific 2.1 sensors.

**Comment by JoakimOgren** [comment]
Same problem, in rc.6 and rc.7 these stopped working:
- Oregon Scientific THGR810 (Oregon Scientific v3.0)
- Oregon Scientific THGR122NX (Oregon Scientific v2.1)

**Comment by weerderhof** [comment]
I cant find my new alecto ws1200 station. What can i do to find him in the ap?

**Comment by nlrb** [comment]
Issue is still present in rc.8.

**Comment by Maxwell70** [comment]
I agree! The problem is present!

**Comment by sjolof** [comment]
Same here. Lost 4 sensors since going to  1.5.6-rc.8 (from older stable release)

**Comment by FrankBakermans** [comment]
Hi All,

Is this on the radar with Athom to fix? I have also a rain sensor that can't be detected because of this bug.

Cheers

**Comment by jeroenvollenbrock** [comment]
Should be fixed in 1.5.6-rc.11

**Comment by nlrb** [comment]
I can confirm that the sensors show up again with rc.11. You rock (as usual) @jeroenvollenbrock.

BTW: did notice a new issues is introduced with rc.11: the `date.toString()` produces output like `Thu Feb 08 2018 18:05:01 GMT+0000 (undefined)`.

**Comment by epjjansen** [comment]
WS-1100 is still showing up in RC11
WS-1200 is not showing up

In insights the WS-1100 is showing less updates after the installation off RC 11
![image](https://user-images.githubusercontent.com/31935273/36030054-00d25c60-0da6-11e8-912c-7a510bce259d.png)
Temperature

![image](https://user-images.githubusercontent.com/31935273/36030096-2133c642-0da6-11e8-81b7-97889397aa2d.png)
Humidity

**Comment by jeroenvollenbrock** [comment]
1.5.6-rc.13 contained an additional fix for this problem, can you confirm it is working again?

**Comment by tobpet** [comment]
I'm on 1.5.6 and none of my oregon sensors  are showing up.
Some of them did in rc.13 but not all of them.

**Comment by nattlip** [comment]
indeed oregon worked on rc13 but not on rc 1.5.6

**Comment by nlrb** [comment]
Athom is aware of this. They had to revert the fix of rc11/rc13, since it was causing issues with KAKU. Hence the situation with the final 1.5.6 is the same as before. They are currently working on implementing a structural solution for 433 that works for all cases.

**Comment by nattlip** [comment]
x10 doesnt work either in 1.5.6 it worked ok under all other firmwares. it is a very robust signal , so what they did i dont know.

**Comment by jeroenvollenbrock** [comment]
We had to revert the rc13 fix due to #2218 We've started working on a more robust solution for the support of the variety of different signals

**Comment by Betib** [comment]
No oregon works anymore for me, 1.5.6 does not work, installed 1.5.7 still does not work!

**Comment by epjjansen** [comment]
WS-1200 is still not showing up with version 1.5.7

**Comment by epjjansen** [comment]
In Insights, 1.5.6 and 1.5.7 are working fine

![image](https://user-images.githubusercontent.com/31935273/36733125-e67ce2e4-1bcf-11e8-829d-098d4177133b.png)
![image](https://user-images.githubusercontent.com/31935273/36733212-2e824b9c-1bd0-11e8-9c72-7469036decca.png)

**Comment by Betib** [comment]
I have used wireless weather sensors since I got my Homey in November with version 1.5.3. Then went over to the exprimental and the three Oregon I have outdoors disappeared. they have only worked well with rc13. The Oregon sensors are THGR238N, THGR810 and THGN122N.

**Comment by nattlip** [comment]
i think Athom should get some external advice , eg from rfxcom also dutch , they know how to to receive and send all domotica rf possible Bert Weijenberg knows it all. There was a guy at Athom that was a wizard at rf but he stopped working for Athom. I have 93 NONoregon users now and weathersenors a lot more i think

**Comment by juuldk** [comment]
Currently running version 1.5.7, and not able to connect 2 Oregon THGR810 sensors.
They don't show up in the list of sensors. 
Looks like there still is work to do on the Homey RF and their QA process to stabilize it.

**Comment by epjjansen** [comment]
The WS-1200 just showed up once after many days

[stats1520340530012.json.log](https://github.com/athombv/homey/files/1785108/stats1520340530012.json.log)

Got the message again that is it offline again

**Comment by zidodiz** [comment]
Samer here on 1.5.7 no Oregon weather sensors showing up and also no Telldus weather sensors.

**Comment by zidodiz** [comment]
Still same on FW:1.5.8 some sensors showing up from time to time but oregon v3 never shows up (app version 1.2.1)

**Comment by azzeman** [comment]
Same here :(

**Comment by juuldk** [comment]
Oregon V3 still not working on newest FW 1.5.8.
Have spent quite some time trying to connect the Oregon THGR810 sensor - with no luck.
Do we know if the Athom people actually respond or include our feedback in their new software releases.

**Comment by zidodiz** [comment]
Hi Juuldk,

I emailed Athom support and got an answer just a couple of hours later, nice. They are aware and are working on a solution. I asked if those sensors will start working again and the answer was I quote:
"Yes, they will work again:)"

**Comment by juuldk** [comment]
Thanks @zidodiz 
Really appreciate your followup with Athom and thank you for the feedback. 
Let's hope they get it working soon, and that they would stop breaking it when they release new versions.  Fingers crossed..

**Comment by twister5800** [comment]
Same here with 1.5.8 :-/

**Comment by gunnang** [comment]
Same here with 1.5.8, just bought my homey to connect my 433Mhz sensors and now it's not working :-/

**Comment by gunnang** [comment]
@jeroenvollenbrock 
Does this:
@jeroenvollenbrock jeroenvollenbrock modified the milestones: 1.5.6, 2.0.0 21 days ago
Mean that you don't aim to fix this until release 2.0, when is that scheduled?

**Comment by nattlip** [comment]
well oregon and weathersensor app wont be wrking good then until then

**Comment by gunnang** [comment]
@nattlip Do you know anything about the release plan for 2.0? When can it be expected?

**Comment by nattlip** [comment]
no i am an ordinary user, i have no inside information

**Comment by Mgerlam** [comment]
Want to inform that Am not able to find Telldus Thermo / Hygrometer item 313160.
Homey fw 1.5.8.
Br
M

**Comment by DIYglenn** [comment]
Unfortunately had issues with 433 in general since I purchased Homey 6+ months ago, and now fullt lost all communication. Hopefully we’ll see better signal for 433 in the future.  
Both a colleague of mine and my dad is looking into Home Automation, and I’ve recommended Homey because it’s the most open central I could find. 
Unfortunately though, they are fully dependent on 433 working, so I’ve got them to wait it out for a while.

**Comment by greycreations** [comment]
I am also running 1.5.9, still not possible to detect Oregon THGR810 sensors (Oregon v3 protocol). When is this going to be resolved?
Is there any planned release date for firmware 2.0?

**Comment by epjjansen** [comment]
Same behavior for version 1.5.11
The WS-1200 just shows up every other day at random intervals 
Then goes offline again
![image](https://user-images.githubusercontent.com/31935273/40651844-fa745a12-6336-11e8-9f0a-61821bd38570.png)

**Comment by glennjacobsen** [comment]
Yeah, I've given up all 433MHz sensors, they show up once or twice every month or so, while RFXtrx433 gets a signal approx every 40 seconds.
I purchased some XIAOMI Aqara sensors (Zigbee) to replace all my sensors, mesh network seems to be the way to go. 
433 Outlets (click on/click off) seems to work fine though.

**Comment by twister5800** [comment]
@greycreations  exactly the same issue and sensor I have :-/

**Comment by DIYglenn** [comment]
Yeah, I've given up all 433MHz sensors, they show up once or twice every month or so, while RFXtrx433 gets a signal approx every 40 seconds.
I purchased some XIAOMI Aqara sensors (Zigbee) to replace all my sensors, mesh network seems to be the way to go. 
433 Outlets (click on/click off) seems to work fine though.

**Comment by nattlip** [comment]
indeed it isvery very long now that wheather sensors arent working, makes my very sad

**Comment by nlrb** [comment]
Yes, agreed. This is not what @jeroenvollenbrock promised when the issue occurred. He would free up his schedule to address this asap. They broke the implementation due to the new hardware revision and reverted the fix because that broke KAKU. And KAKU is more important. Basically this app is not important to Athom. Do I need to remove it from the store again?

**Comment by juuldk** [comment]
I must say that I’m very disappointed. Athom is turning out to become the failure that I wish they wouldn’t end up being.
They have limited resources and still they have put themselves between a number of chairs. 
Focusing on mobile client, while core product isn’t working. Building out new features and apps to support new brands, while other brands and features that used to work now stopped working. Prioritizing local dutch buyers by giving KAKU priority over global buyers and global brands.
I did raise this issue many months back and was told Athom would fix it. 
Here we are, and the only thing I receive is messages with more ‘noise’ about new features and other stuff, and still no fix to or official update on the core product issues. 
Over-promise and under-deliver is a guaranteed route to failure - and I’m not gonna waste more time on this.
Will start looking for a more professional alternative. Maybe less features - but at least they would work.

**Comment by solpojke** [comment]
I just received my Homey and it can't find any of my 433 MHz-sensors, which was the reason for me to by Homey. Should I return it?

**Comment by Quart666** [comment]
Over 6 month now...what happens ?

**Comment by juuldk** [comment]
Safe yourself from disappointments - use the Homey as a good looking door-stop. The lack of ‘fixing core problems and lacking functionality” is a joke. 
Love their ambitions and  wished it would come through - but this has now turned Into an amateurish setup with a number of people working hard to deliver on their original promises - but they are not even aware how far they are off on delivering against their promises.
I feel sorry for them - great concept, but really bad execution. 
And I’m done waiting for some Magic to happen one odd day...

**Comment by nlrb** [comment]
Based on the release notes of 1.5.13-rc.9 installed that version, expecting this issue to be fixed. But now have lost all Oregon Scientific signals (and maybe more).
Should this be fixed in 1.5.13-rc.9 or is in only planned for 2.0.0?

**Comment by jeroenvollenbrock** [comment]
This should indeed be fixed in 1.5.13-rc.9 and we have received reports of this being solved during our alpha test period. Could you be a bit more specific as to what is not working properly?

**Comment by nlrb** [comment]
Receiving signals from THGN800, THGR810, BTHGN129 etc. that would be received before do now not work or very sporadic. They are received properly by the Oregon Scientific base station.

**Comment by jeroenvollenbrock** [comment]
Could you provide recordings of these transmissions taken from https://developer.athom.com/tools/signals so we can reproduce the issue?

**Comment by nlrb** [comment]
A recording of the BTHGN129 signal should be in here. If you need a clean recording, I'll need to do it some other time.
[recording.zip](https://github.com/athombv/homey/files/2372458/recording.zip)

**Comment by Maxwell70** [comment]
After update 1.5.13-rc.9 my sensors (THGN132N) is not visible in Homey! The developers broke this feature in December 2017 ((((((((

**Comment by Maxwell70** [comment]
After update 1.5.13-rc.11 my sensors (THGN132N) is not visible in Homey!

**Comment by Maxwell70** [comment]
The sensors are visible only in the immediate vicinity of the Homey (10-20cm) %(((((

**Comment by Ogge66** [comment]
I have the THGN800 which is less than 2m from Homey but still no luck...

**Comment by Ogge66** [comment]
Sorry I meant the WGR800

**Comment by jenslindskov** [comment]
I can confirm that all my Oregon sensors (THGR810) finally came back after installing 1.5.13-rc11! They had been missing / working very poorly since december last year when the stable branch became unstable.

**Comment by jwikman** [comment]
@jeroenvollenbrock Would it be possible to do a similar update for Auriol sensors?
