### ISSUE TITLE
Newly added Zigbee devices seem to be added twice and don't work properly

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#2078]
**Metadata**

* **Homey Version**: 1.5.6-rc.7
* **Homey Log Code**: 255F20D831
* **Smartphone Platform**: N.A.
* **Smartphone App Version**: N.A.

**If related to a Homey App:** N.A.
* **Homey App Version**: 
* **Homey App Log Code**: 
* **Affected Devices (preferably product codes)**: 

**What did you try to achieve?**
Add new Zigbee devices. I've received some new Xiaomi Aqara devices and when adding them I found this issue. To make sure it wasn't an App issue I also added a Zigbee device from a different vendor and type.

**What did you expect as result?**
The device to be added once and working as earlier added devices of the same type.

**What was the result?**
Devices seems to be added twice and they don't seem to work.

Devices 1,2 and 3 were added on a previous firmware version and function as expected. Devices 4 (5) and 6 (7) report no data, devices 8 (9), 10 (11), 12 (13) and 14 (15) seem to work as expected.

![image](https://user-images.githubusercontent.com/16610696/34071379-cbaffbec-e275-11e7-93da-bcbab77a516f.png)

![image](https://user-images.githubusercontent.com/16610696/34071411-42be1836-e276-11e7-889d-7cc298834489.png)
![image](https://user-images.githubusercontent.com/16610696/34071415-586ab824-e276-11e7-92ee-7723e34d7cc0.png)

**Any other remarks**
The names in the Zigbee connections graphs are cut off and the Nodes pane does not scroll, other than that I like the tools we've been given.

**Comment by daneedk** [comment]
After deleting the not working devices 4 (5) and 6 (7) they were no longer visible in Homey's UI but remained in the Tools Network view and Tools Nodes pane as Unknown. A reboot or PTP did not fix that. 
When I added one of the sensors again it seemed to be recognised an 'given' it's previous spot 4 (5) and now the sensor did work as expected.

![image](https://user-images.githubusercontent.com/16610696/34071752-b3bf7ea8-e27b-11e7-989c-19f717a501f4.png)

After that I added the other sensor again, but now it seems the numbers were somehow shifted, so I have no idea if there a real relation between a device and the number under which it's shown on the Tools pages. Fortunately for me the sensor now also works as expected but the issue that the devices seem to be added twice still exists.

![image](https://user-images.githubusercontent.com/16610696/34071857-8804c302-e27d-11e7-8f26-24a852e52c14.png)

**Comment by SkorpionNL** [comment]
I also experience this issue on RC7.

**Comment by mruiter** [comment]
Also have this problem. Added 8 devices got 16 in exchange.
Zigbee working crap now

**Comment by RobinBol** [comment]
Thanks for reporting, this should be fixed in the next build.

**Comment by fvhuizen** [comment]
For me the same issue. An existing Aquara weather device popped up correctly and two new devices are show up double
<img width="1119" alt="schermafbeelding 2017-12-31 om 11 04 00" src="https://user-images.githubusercontent.com/25953849/34460927-7a83112e-ee1d-11e7-8cba-1adb6c3a7ed4.png">

**Comment by daneedk** [comment]
Just updated to 1.5.6-rc.11 and saw the devices added on rc.7 still showed 2 entries in the graph.

I've removed a sensor to see if this would clear up (and add it again to see if adding is working as it should) but after removing it now shows an unknown device:

![image](https://user-images.githubusercontent.com/16610696/35989876-a98a86d8-0d02-11e8-8b3d-bd026d268643.png)

Please advice how to get rid of it

**Comment by daneedk** [comment]
Gone through all devices, removed the devices that showed up twice and added them again, all seems to be good, not seeing the behaviour for which I created this issue 
![image](https://user-images.githubusercontent.com/16610696/35994650-66364778-0d11-11e8-8e56-93348ecc29fb.png)

**Comment by RobinBol** [comment]
Generally a reboot, or pairing/removing a ZigBee device will get rid of any left over 'unknown devices', I'll close this issue for now. If the behavior reoccurs let us know!
