### ISSUE TITLE
Latest updates prevent Homey connecting to hidden WiFi-networks

### ISSUE THREAD

**Issue by rkokkelk** [athombv/homey#2142]
Since latest releases, Homey has failed trying to connect to hidden networks. My previous setup had Homey connect to a hidden network which worked fine. With the recent releases, after applying the updates, the connection to Homey was lost. I found out that Homey was nog longer on the IoT network.

Using the restore functionality (holding homey upside down) I tried to reconfigure the WiFi-network. Again Homey could not connect to the hidden network, other devices at the time could. Reconfiguring the network to Broadcast did result in Homey correctly connecting to the network. However, while homey was successfully connect to the network, I again reconfigured the WiFi-network to stop broadcasting, and Homey lost the connection immediately. 

Would like to use Homey with a hidden network. Thank you for your assistance.

* **Homey Version**: 1.5.6-rc.8
* **Homey Log Code**: 9CFD0EF42E

**What did you try to achieve?**
Connect Homey to a hidden network

**What did you expect as result?**
Working WiFi internet connection

**What was the result?**
Homey could not connect to the network.

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.5.6 (final)

**Comment by rkokkelk** [comment]
As mentioned in #2337, I still have issues with Homey connecting to hidden networks. If more information is required, please let me know.
