### ISSUE TITLE
Stuck at 'Already a pairing session active'

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#240]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Include a Fibaro Wall Plug Z-Wave device.

**What was the result?**

Wall Plug inclusion did not complete. Stuck very long on 'Interviewing device 1 of 1'. After a long time that a pop-up appears (with I believe) 'Already pairing active'. Went to Z-Wave to remove the node (which worked as a charm). Wanted to include another device, but immediately got the pop-up 'Already a pairing session active'. This keeps on happing, which means pairing is no longer possible.

**What did you expect as result?**

1. That the Fibaro Wall plug pairs without a problem.
2. That if pairing fails, you can still pair another device.

**Any other remarks**

Proper exception handling & testing please.

**Comment by ocatie** [comment]
Can you repeat the problem after a power cycle?

**Comment by nlrb** [comment]
Yes, exact same thing.

First pop-up:
![error_pairing_active1](https://cloud.githubusercontent.com/assets/11725674/13334908/b182fa9a-dc0e-11e5-9ad3-692f793e70dd.png)

Then when trying to add a z-wave device:
![error_pairing_active2](https://cloud.githubusercontent.com/assets/11725674/13334921/be185250-dc0e-11e5-9732-8032cf838c9e.png)

**Comment by djeskoswe** [comment]
same here with TKBHome switch ,

**Comment by Muyz** [comment]
Same here with dimmer

**Comment by ocatie** [comment]
Could you please powercycle Homey, reproduce the problem and send us the log.

You can send us the log using the button in Settings -> System -> Send Log. A code will be generated that you can place here.

**Comment by nlrb** [comment]
Yes, I noticed the 'Send a log' button in 0.8.20.

I'd first like to know what information is being sent before sending a log file. So in essence I want to review it before sending.

**Comment by djeskoswe** [comment]
will send my log when i come home ,

**Comment by djeskoswe** [comment]
16E427B934

**Comment by ocatie** [comment]
@nlrb The log is a dump of all kernel output. It doesn't contain any personal information.

Thanks djeskoswe. I see that during the interview a command isn't answered by the device you're trying to pair. A message that an error should the popup in the pair wizard. I'll look into that. Because the browser doesn't receive a callback it resends the start pairing command and gets a "Pair session active" error.

In 0.8.21 I've improved the resend timeouts for battery devices. This should decrease the error rate in the interview process.

**Comment by ocatie** [comment]
@djeskoswe could you please post a screenshot of your browser console log after the first "another pair session active" popup?

**Comment by djeskoswe** [comment]
ctrl+shift + I and the console when i run the pair ?   ( new to this setup )

**Comment by ocatie** [comment]
Yes

**Comment by djeskoswe** [comment]
is this right ?  

![capture](https://cloud.githubusercontent.com/assets/17300121/13361921/eda699ec-dcc1-11e5-8ea4-1d2fbbce3998.JPG)

**Comment by djeskoswe** [comment]
![capture](https://cloud.githubusercontent.com/assets/17300121/13361944/091e827a-dcc2-11e5-9734-392bb728ff84.JPG)

**Comment by djeskoswe** [comment]
its the fibaro wall plug ,

**Comment by Muyz** [comment]
So, I hope that a fix/solution for non-battery powered devices will also be available. At my place, it's the non-battery powered devices that fail. The Fibaro battery-powered sensor devices work flawlessly.

**Comment by djeskoswe** [comment]
@ocatie  did the screenshot help you ?

**Comment by ocatie** [comment]
Yes they do. I'm having trouble reproducing the error. Looking at the log it seems the request doesn't reach the driver. Do you have a direct connection to Homey or through the cloud?

I've added more internal logging in 0.8.21. Please try to reproduce and send the log again at 0.8.21.

**Comment by djeskoswe** [comment]
@ocatie  , direct connection 

Can i do any more testing ?

**Comment by RemonBerends** [comment]
@ocatie Well i read here about version 0.8.21 and improvement of Zwave devices. Does it means that this version is already available? And if yes, how to update to this version?

**Comment by ocatie** [comment]
0.8.21 is not yet available. I think the issue will be fixed in 0.8.22. I've also implemented improved logging in that version so I can get more info if the fix didn't worked.

**Comment by nlrb** [comment]
In 0.8.22 the interview process of a Fibaro wall plug still fails. However, it now ends with an error message that the interview failed, but you should be able to switch the device on & off. A z-wave device is added, but it cannot be switched on or off.

**Comment by ocatie** [comment]
Then still something goes wrong during the interview. If the interview fails the device is added as a socket so you can control the device using Basic Set commands.

In 0.8.23 I've fixed a bug so you can interact with the card.

**Comment by djeskoswe** [comment]
My tkb switch works,  but fibaro wall plug does get a non response on-off device.

**Comment by ocatie** [comment]
Fixed in 0.8.24

**Comment by djeskoswe** [comment]
@ocatie,  After some hours the device is dead,  and reboot i needed!! 

Fixed in. 24 release or you need log?

**Comment by ocatie** [comment]
Which version are you on, which device do you mean and what do you mean with dead? With every issue a log is helpfull.

**Comment by djeskoswe** [comment]
Im on. 22 the socket get unavailable,  dead and cannot switch off or on.  Do you want log now or after next reboot?

**Comment by ocatie** [comment]
Please reboot, reproduce and send log. Saves us a lot of time filtering if Homey has been on for a long time.

But if the issue is your device gets unavailable, please post your log in #175 to keep things organised.

**Comment by djeskoswe** [comment]
did a reboot but socket wont get back after reboot or restart/ refresh zwave , need log ?

**Comment by djeskoswe** [comment]
added log to 175 case : 35571BE9A1

**Comment by djeskoswe** [comment]
version .24 and now i can add fibaro wallplug as on/off device , but no power reading

**Comment by Muyz** [comment]
With .24 this is what I get:
![schermafbeelding 2016-03-16 om 17 53 56](https://cloud.githubusercontent.com/assets/17163901/13821018/27df01d4-eba0-11e5-834c-8c06c34e47be.png)

**Comment by Muyz** [comment]
So, what's the plan on solving this issue? Can I/we help? If zwave is not working properly, Homey is essentially a paperweight for me. I do understand fixing issues takes time, but the radio silence worries me.

**Comment by ocatie** [comment]
Happy to announce, I was finally able to reproduce the issue and it is fixed!

**Comment by nlrb** [comment]
With 0.8.27 the interviewing process still fails. It does add an on/off switch, but this only works until Homey is reboot. After a reboot, the device shows a broken connection link with 
![error_timeout_waiting_for_report](https://cloud.githubusercontent.com/assets/11725674/14227764/3d0c1e4e-f905-11e5-9840-fdb525e91819.png)
The 'broken link' makes that you cannot even delete the device, as that button is blocked (same as for device settings).

**Comment by Muyz** [comment]
Same problems here. It is still impossible to add some dimmers. Sometimes a dimmer shows up as a single switch (1 device interviewed) and sometimes 3 devices are interviewed, but the device type is not detected. In all cases, the device(s) that is/are added are not usable. 

So yes, the 'another pair session active' error does not show up anymore, but in the end the dimmers are still not usable. 

If I can help by testing/sending logs, let me know.

**Comment by ocatie** [comment]
@nlrb Is the "already pairing session active" issue solved? I closed the issue because I fixed the bug that I noticed in the logs and caused this issue. If you have another issue please open a new issue to keep things organised. If the issue is related you can link it by mentioning the issue number starting with a #.

**Comment by nlrb** [comment]
Changed the title for your convenience :-). The 'already pairing session active' does not occur anymore, but that was only part of the problem.

**Comment by ocatie** [comment]
Changing the title isn't ideal because labels etc. are then shared and don't apply for both issues. I've created a new issue regarding the Fibaro Wall Plug #410.

**Comment by peaoo** [comment]
@Taco Ok, thanks! Here is the log: 4525EC35BD 
I tried to connect it, but it timed out after a while with the error "Another Pairing Section active".

**Comment by ocatie** [comment]
Please try again on 0.8.30

**Comment by peaoo** [comment]
The problem is still there after .30 but it is different:
The pairing process seems to stuck at "Interviewing device 1/1" and there is no more timeout. But the screen was there for over 10 minutes and nothing changed. When I closed it and tried to do it again, the "Another Pairing Section active" popup prompted. After a restart I was able to pair the lock, but it still has no lock/unlock possibilities. Log: 9D86736D6C

**Comment by peaoo** [comment]
Still there after .32. Same problem. I guess the error is caused that the "Interviewing device 1/1" window seems to become stuck and has to be closed manually. Here is a step by step how this error occured:

Z-Wave, add Device -> Device Found -> Interviewing device 1/1 -> waited 10 minutes -> closed the window with the X -> Z-Wave, add Device -> "Another Pairing section active" -> waited 10 minutes -> "Another pairing section active.

**Comment by freemann** [comment]
Tried to reproduce a other issue and also run into this issue.
"Interviewing device (1/1)" took very(!) long and eventually the well known "...already...." message came up.
Here's a log; 7F7AE17024

**Comment by luccie007** [comment]
Looks the same like my issue:
https://github.com/athombv/homey/issues/426
