### ISSUE TITLE
homey-api lastUpdated not updated with new timestamp

### ISSUE THREAD

**Issue by janlemv** [athombv/homey#2504]
**Metadata**

* **Homey Version**: latest stable
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

devices = <homey-api>.devices.getDevices  and attaching eventListener 
State gets returned, and device.state gets updated with new state.
Can not see that device.lastUpdated gets updated with new values

**What did you expect as result?**

Actual timestamp in lastUpdated for when the triggered state changed

**What was the result?**

Old values sticks .

var dump device.state and device.lastUpdated
Triggered at time=0:
Master Bedroom Roof light changed:  { onoff: true, measure_power: 0, meter_power: 0.14 }
{ onoff: '2018-06-10T17:56:09.430Z',
  measure_power: '2018-06-10T17:56:09.837Z',
  meter_power: '2018-06-10T17:15:06.883Z' }
event occured
OK

Master Bedroom Roof light changed:  { onoff: true, measure_power: 10, meter_power: 0.14 }
{ onoff: '2018-06-10T17:56:09.430Z',
  measure_power: '2018-06-10T17:56:09.837Z',
  meter_power: '2018-06-10T17:15:06.883Z' }
event occured
OK

Triggered at time + 20 sec:
Master Bedroom Roof light changed:  { onoff: false, measure_power: 10, meter_power: 0.14 }
{ onoff: '2018-06-10T17:56:09.430Z',
  measure_power: '2018-06-10T17:56:09.837Z',
  meter_power: '2018-06-10T17:15:06.883Z' }
event occured
OK

Master Bedroom Roof light changed:  { onoff: false, measure_power: 0, meter_power: 0.14 }
{ onoff: '2018-06-10T17:56:09.430Z',
  measure_power: '2018-06-10T17:56:09.837Z',
  meter_power: '2018-06-10T17:15:06.883Z' }
event occured
OK

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Fixed in version 118

**Comment by janlemv** [comment]
@jeroenvollenbrock is it fixed already or fixed and pending for release? I'm still getting the same results.
