### ISSUE TITLE
[com.sonos] Starts playing on wrong speaker

### ISSUE THREAD

**Issue by YD85** [athombv/homey#2709]
* **Homey Version**: 1.5.11
* **Homey Log Code**: B9C3613816
* **Smartphone Platform**: IOS
* **Smartphone App Version**: latest

**What did you try to achieve?**
I want to set up a flow that i can activate when i get home. In this flow i want to trigger one or more sonos speakers to start playing. 

**What did you expect as result?**
Correct speaker or sonos group starts playing in correct volume

**What was the result?**
When I attempt to define a flow to play music on sonos, it is not working as you would expect. 
- by dragging a sonos speaker in the THEN area of the flow; not playing single nor grouped speaker
- by dragging a music item in the THEN area of the flow & select active speaker: wrong speaker is starting to play.

**Any other remarks**
Sonos system is heavily reliant on the grouping functionality. This changes a lot; so it is hard to configure a flow that behaves correctly with groups. e.g. is is likely that the individual speakers have their own play list stored in the back, but when you group them the play list of the lead-speaker is played. However, in Homey it is not possible to select a group or create a group. Ideally you create a group in a flow and then plan accordingly. By this you are always correct.

**Comment by Rocodamelshe** [comment]
Copy of Lots of issues on GH.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.

**Comment by chrisboer** [comment]
Not fixed, can not even select Sonos speaker under music 
![afbeelding](https://user-images.githubusercontent.com/23163409/46281933-72554500-c570-11e8-841a-e7fb96b0c340.png)

**Comment by WeeJeWel** [comment]
The 4.x Sonos app doesn't support Homey Music anymore. (https://blog.athom.com/take-speech-music/)

**Comment by chrisboer** [comment]
> 
> 
> The 4.x Sonos app doesn't support Homey Music anymore. (https://blog.athom.com/take-speech-music/)

Ok changed it with URL playing now directly from Sonos app works great, so don't need the Radio app anymore
