### ISSUE TITLE
[nl.klikaanklikuit] The doorbell ACDB-6600 can't be triggered after latest update, release v4.0.2 - 31.07.18

### ISSUE THREAD

**Issue by ppagard** [athombv/homey#2717]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by mruiter** [comment]
Did you do a ptp of youre homey. A Pull the plug

**Comment by Dijker** [comment]
Here I tried both doorbel's on both the old and new  version klikaanklikuit and they work here. 
If you tried a Pull the Plug, have you tried pairing it again?

**Comment by ppagard** [comment]
I will try to pair it again to night!

**Comment by FingolSE** [comment]
I have the same problem, since the update a generated code for the doorbell may be successfully programmed/learned in the doorbell (note that the signal is not sent until I press test during program mode. So I can test and successfully trigger the doorbell from Homey then when including a trigger card in a flow there is no sound from the doorbell.

**Comment by floreseken** [comment]
I'm having the same problem.. and this sucks bigtime. Device can be paied and testes successfully but does not work from a flow.

**Comment by gijsje** [comment]
Same here

**Comment by nieuwton** [comment]
Homey 1.5.13 and Kaku 4.03 beta. The pairing procedure works. The test button activates the doorbel sound. But when used in a flow, the sound is not activated. Are the two signals different?

**Comment by ppagard** [comment]
Same for me. I can pair and successfully test the doorbell, but it won’t work in a flow! Pleas fix this ASAP!

**Comment by nieuwton** [comment]
Kaku 4.04 beta. Doorbell ACDB7000C. After pairing, the doorbell is ringing at random moments with intervals of minutes. A flow does not activate a ring.

**Comment by nieuwton** [comment]
Kaku 4.06 beta. Doorbell ACDB7000C. Still the same problem

**Comment by KyleAthom** [comment]
Hi All,

We have reproduced this issue and are planning to include a fix in the upcoming stable version of the KlikAanKlikUit app.

**Comment by floreseken** [comment]
Is there an eta for that? 

And why not fix it right now in the beta?

**Comment by FingolSE** [comment]
KAKU updated to 4.07, issue remains...

**Comment by KyleAthom** [comment]
Correct. As there where many more issues with sockets and other important devices we have decided to already release a stable build. In this way those issues are fixed. The doorbell issue will be one of the next fixes and be included in the next stable!

**Comment by runner780** [comment]
Same here with ACDB6600 and ACDB7000C both of them stopped responding to Homey. The work with the button at the door though.

**Comment by runner780** [comment]
Is there an ETA for the doorbel fix? Now i do not notice when someone comes through the backdoor.

**Comment by KyleAthom** [comment]
We have just published a new beta version (4.0.9) of the app that includes a potential fix for this problem.
You can install it to try it out, or wait until this (or a higher version) is relased in the stable channel. Please be aware that once you've changed to the beta channel you can't go back to stable without deleting all your devices and flows!

**Comment by runner780** [comment]
Hello Kyle, had to re-add the 6600 but now it's working again THX! The 7000 still does not though.

**Comment by nieuwton** [comment]
Hi Kyle, I can confirm that ACDB-7000C is working again. Thanks.

**Comment by gijsje** [comment]
Both are working again. Thanks

**Comment by ppagard** [comment]
6600 Is not working for me! Do you copy from button or create new code from doorbell?

**Comment by gijsje** [comment]
I had to remove all the old codes from the device and then re add it and it was working

**Comment by KyleAthom** [comment]
@ppagard I've tried both methods and they worked fine. Have you tried to remove all the pairings from your doorbell?
