### ISSUE TITLE
[com.somfy] Somfy RTS stopped working after update of homey to 1.5.12

### ISSUE THREAD

**Issue by fupanda** [athombv/homey#2806]
Homey Version: 1.5.12
Homey Log Code: BCB6584234
Smartphone Platform: Android
Smartphone App Version: Homey 2.4.7 - Build 77 and  Homey (preview) 0.8.115

Homey App Version: Somfy RTS v3.0.3 and v3.1.1
Homey App Log Code:  a84891f3-7b12-493a-b8be-f1a887b01096
Affected Devices (preferably product codes): Somfy RTS 74800

Can not operate the somfy rts device anymore, has worked stable for more than a year. It seems to stopped working after the update of homey to 1.5.12.  

Tried to reset the somfy device multiple times. The remote control works fine, but homey doesn't respond to any command. 
Tried to reconnect it to homey, but with no success. 
Tried to restart homey multiple times, also no success
Tried to unplug homey and the somfy device, also no success
Also tried the beta version of the Somfy RTS app v.3.1.1, but also no success.

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.5.13

**Comment by kevsinclair** [comment]
Got the same issue, totally stopped working.

**Comment by behgez** [comment]
@jeroenvollenbrock 

still not working in 1.5.13. Same behavior. Also when adding Forest Shuttle through generate signal, nothing happens. Adding with the copy signal from remote, the behaviour as desribed before happens (works during testing, but not anymore after adding)

> Same here. I added the somfy shutters again. During device adding (which only works with the copy signal), when you can test the up/down before pushing the final 'next', the triggers work and the curtain opens/closes. But when you click next/finish and the device is added to Homey, it is not working anymore when pressing the tools icon in the top corner and/or adding it to a flow.

**Comment by behgez** [comment]
@jeroenvollenbrock can you please update on the status?

**Comment by SailingDuck** [comment]
I also had problems but it started to work by setting the signal length setting to a higher value. Mine was at shortest signal length, now working at normal signal length. Im also on rc11.

**Comment by behgez** [comment]
@SailingDuck 
I only have the option to invert the signal when I click that.

**Comment by fupanda** [comment]
I tested again with the release of 1.5.13 and it works.

**Comment by behgez** [comment]
I tested it and it works. But it has nothing to do with 1.5.13. It is the Beta release of the App itself (Forest 3.0.1) that fixed it.
