### ISSUE TITLE
Sonos 4.0.5 Beta not playing Spotify Artist

### ISSUE THREAD

**Issue by coenboomkamp** [athombv/homey#2833]
* **Homey Version**: 1.5.12
* **Homey Log Code**: 851E30F841

* **Homey App Version**: Sonos 4.0.5 BETA
* **Homey App Log Code**: dd749eb2-78e9-4c15-bc8e-f9cd068fa07a

**What did you try to achieve?**
Play a Spotify artist.

**What did you expect as result?**
Sonos to play the selected artist in my flow card.

**What was the result?**
Got a "500" error

**Any other remarks**
![img_0454](https://user-images.githubusercontent.com/34875500/45806168-a56e1d80-bcc0-11e8-8698-1cd51ac1de99.jpg)

**Comment by moekdegroot** [comment]
I have the same issue. However I get the error with all spotifycards.
@coenboomkamp do your other spotifycards work?
I'm running 1.5.13-rc.11 by the way.

**Comment by coenboomkamp** [comment]
@moekdegroot yes i also have it with all the Spotify cards.

**Comment by moekdegroot** [comment]
Thanks!
@WeeJeWel , any idea what's causing this?

**Comment by WeeJeWel** [comment]
Just to verify: did you login with your Spotify Premium account on the Sonos device, using the Sonos Desktop/iOS/Android app?

**Comment by coenboomkamp** [comment]
Yes i did @WeeJeWel. @moekdegroot you too?

**Comment by moekdegroot** [comment]
Now that I think of it, I had to reset my spotify password last week.
Completely forgot because all is still working from within the sonos app (my playlists still show etc).
I'll log in and out this afternoon and see if that resolves anything and report back.

**Comment by moekdegroot** [comment]
@WeeJeWel and @coenboomkamp 
I just came home and checked if things worked as they seemed when I was at work.
No go. I get the error again (701 when the region setting is set to the us and 800 when it's set to eu).
What I tried:
First I removed and re-added my spotify premium account in the sonos app. Didn't make a difference.
I then disconnected all phones from the wifi to see if that made a difference (which it didn't) and also made a wifi hotspot on my phone and connected my laptop to it because that resembled the situation as it was earlier when I didn't get an error (when my macbook was connected to the internet at work). Also didn't help. Anything else I can try?

**Comment by WeeJeWel** [comment]
I could reproduce the issue, and then after some testing it suddenly worked again...

Coudl you try with the newest version v4.0.6?

**Comment by moekdegroot** [comment]
Sorry @WeeJeWel , the app keeps crashing after installing.
Also tried uninstalling first and uninstall + PtP.
The app says you've been notified but also send you a log: B91E6E7250

**Comment by WeeJeWel** [comment]
Sorry about that. I just published v4.0.7 which doesn't crash.

**Comment by moekdegroot** [comment]
No prob @WeeJeWel , just installed 4.0.7 but still getting the same errors I mentioned above.
@coenboomkamp does it work for you?

**Comment by Rocodamelshe** [comment]
Same error here with playing a TuneIn station.

![sonos error](https://user-images.githubusercontent.com/19249884/45899880-69c97580-bdde-11e8-9dc7-1459c8988b24.png)

**Comment by coenboomkamp** [comment]
Hey everyone, sorry had some busy days, the playlist card for Spotify works for me now. I'll do some more testing and let y'all know

**Comment by coenboomkamp** [comment]
@moekdegroot & @WeeJeWel So all my Spotify cards work now, (track, album, artist, playlist) i got 4.0.7. installed. I just can't find my own playlists, and they are not on private, also tried to find some of my friends. No luck... 

Maybe a suggestion for a card would be to enter a URL from Spotify? Then you can add whatever you want, tracks, albums, playlists etc..

And a suggestion is to show the username at the Playlist card, there are a lot of duplicate playlists out there, when the username is shown you can find your playlist faster.

**Comment by off112a** [comment]
Hi, I have the same problem that Spotify card doesn't work. And can't find any of my own Spotify playlist. 

![skarmavbild 2018-09-22 kl 16 26 05](https://user-images.githubusercontent.com/22722009/45918252-5f61b700-be84-11e8-8baa-499fe3e737ca.png)

**Comment by coenboomkamp** [comment]
Still weird that it does work for me..
![schermafbeelding 2018-09-26 om 08 18 57](https://user-images.githubusercontent.com/34875500/46060853-df2da100-c164-11e8-8a64-5be46426a565.jpg)

Any idea @WeeJeWel why we can't find our playlists?

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
