### ISSUE TITLE
[com.sonos] Describe your issue here

### ISSUE THREAD

**Issue by DickvanderMaal** [athombv/homey#2846]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**: IOS
* **Smartphone App Version**:

**If related to a Homey App: Sonos
* **Homey App Version**: 4.07
* **Homey App Log Code**: 
* **Affected Devices (preferably product codes)**: Sonos

**What did you try to achieve?**
Select a Radio station

**What did you expect as result?**
That Sonos select the requested radio station 

**What was the result?**
Sonos.unknownMediaRequest

**Any other remarks**
It works fine in 4.05

**Comment by TedTolboom** [comment]
@DickvanderMaal exactly the same issue I'm exeriencing...

Let me support this issue, instead of making yet another duplicate issue...

After update to Sonos app version 4.0.7, the "Play a TuneIn Station" action cards finishes correctly (green check mark):
![image](https://user-images.githubusercontent.com/17163431/45950116-b390a680-bffe-11e8-9578-03dd24869cc5.png)

The radio station will not start playing, instead the following error message is shown in the Sonos app:
`sonos.unknownMediaRequest`:
![image](https://user-images.githubusercontent.com/17163431/45950161-eb97e980-bffe-11e8-8aac-8b146bdac844.png)

This flowcard has been working well on release 4.0.5

The unique log ID (sonos app) is: 67bec051-b72a-47a3-a9a2-c5ecce9e748b

@WeeJeWel this should be easily reproducable at your setup. Please let me know if I can support in additional trroubleshooting.

@DickvanderMaal I'd suggest to change the title of this issue to: "[com.sonos] sonos.unknownMediaRequest when playing TuneIn Station as of v4.0.7"

**Comment by DickvanderMaal** [comment]
Agree, thanks

Verstuurd vanaf mijn iPhone

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9

**Comment by chrisboer** [comment]
Still an issue in 04.13 

![afbeelding](https://user-images.githubusercontent.com/23163409/46281573-5f8e4080-c56f-11e8-9869-c4d15682a6da.png) 

The error message "jack not plugged"

**Comment by TedTolboom** [comment]
Try the "Play a TuneIn Radio" action card....

**Comment by WeeJeWel** [comment]
Yes, the 4.x Sonos app doesn't support Homey Music anymore.

**Comment by chrisboer** [comment]
Ok clear
