### ISSUE TITLE
[se.nexa] MYC-2300 get lost after 2-3 days

### ISSUE THREAD

**Issue by fhmattsson** [athombv/homey#2848]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**: Any
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: Nexa v1.0.5
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: MYC-2300

**What did you try to achieve?**
Install and use Nexa MYC-2300 devices

**What did you expect as result?**

**What was the result?**

Same issue as #2813 
I install the MYC-2300 devices, and 2-3 days later the device is disabled/unchained in Homey with the additional information "invalid_device_data".

It happens to all devices of  MYC-2300 type.

All devices has benn added individually

If the Nexa App is restarted the problem disappears for another 2-3 days

**Any other remarks**

**Comment by KyleAthom** [comment]
Hi @fhmattsson ,

I've paired a MYC-2300 to see if I'm able to reproduce the issues.
Do you have any flows that are triggering the socket?

**Comment by fhmattsson** [comment]
I have flows that turns on/off lights. In a group of lights it's only the MYC-2300's that disappears. Sometime only one goes "invalid_device_data", sometimes all in the group.

**Comment by fhmattsson** [comment]
![homey](https://user-images.githubusercontent.com/43251375/46034944-2a629800-c102-11e8-9528-499c17042b9a.png)
 First one "lost"

**Comment by torbenaa** [comment]
Exactly the same issue here with my CMR-101.
My EYCR-2300 switches ( on/off ) and EYCR-201 are working fine.

**Comment by KyleAthom** [comment]
I have tested a MYC-2300 for more then a week now and the issue didn't show up unfortunately :(
Did you try and re-add the device to see if the error stays?

**Comment by fhmattsson** [comment]
Yes, Multiple times.

I have had the same issue with KlikAanKlikUit. I have moved them between KlikAanKlikUit and Nexa.
The problem occurs after 1-2 days.

**Comment by fhmattsson** [comment]
What is the reasons for indication of "invalid_device_data"?

**Comment by KyleAthom** [comment]
Can you try and pair it as another device? Usually we advice against this, but I'm curious if this works. If it does, I can find out if it's device related or a more common problem.
The EYCR-2300 might be a good alternative.

**Comment by fhmattsson** [comment]
Same issue with EYCR-2300

**Comment by torbenaa** [comment]
> Exactly the same issue here with my CMR-101.
> My EYCR-2300 switches ( on/off ) and EYCR-201 are working fine.

Well - now my EYCR-2300 switches are also failing. There is no "invalid_device_data" for these - they just won't turn on/off.

Seems a bit random when and which devices are failing. This is quite a big issue for me, since most of my lights are now controlled via Homey :(

**Comment by Mylleranton** [comment]
Also have the same issue, seemingly random which device gets marked as invalid. Have only used MYC-2300 devices.

**Comment by torbenaa** [comment]
Any news on this issue, KyleAthom ?
Please let me know if you need anything from my side ...

**Comment by KyleAthom** [comment]
We're still investigating on this one. Hopefully we can release a beta version for both Nexa and KlikaanKlikuit which will at least allow us to get some more insights in what is actually happening.
Please do note that the "invalid_device_data" error is not the same as devices that are available in Homey but not responding.

**Comment by torbenaa** [comment]
Just upgraded to latest firmware. After the upgrade, the Next app was missing, and all devices were gone.
Added all my Nexa devices again, and for a few minutes everything worked. Now the first device is reporting "invalid_device_data"

**Comment by KyleAthom** [comment]
I'm sorry to hear that! Which version of the firmware did you install?
You might want to contact support at supprt@athom.com so that we can take a closer look.

**Comment by KyleAthom** [comment]
A new update for the Nexa app will be available as a beta as soon as it passes it's internal tests! It should fix this issue.

**Comment by torbenaa** [comment]
It looks like 1.0.6 beta does not solve the problem.
Same symptoms...

**Comment by Dijker** [comment]
@torbenaa 
In the changelog of 1.0.6 I see: 
- Added logging to gain insights in possible signal errors.

`The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).`

Please be as detailed when it happens,. do you use a Nexa Remote? What Type? 
Can you reproduce? 
Does it happen after using one of the buttons? 
(maybe you have to try to use the device from Homey before you can see it in the interface t is broken. 

Please send a Log and reply the Code and any additional information here....
