### ISSUE TITLE
Adding volume device makes trigger to get send twice

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#285]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Add a 'Set volume' action to a flow.
I have 2 flows that interact. 
Flow 1 waits for a KaKu button to be pushed. When pushed it executes 2 actions: a) Pulse the LED ring b) send a command to the OpenTherm Gateway.
![flow1](https://cloud.githubusercontent.com/assets/11725674/13471133/93e58ea8-e0af-11e5-881f-9f1564468620.png)

Flow 2 waits for a response from the OpenTherm Gateway and will say the response. When there is no 'Set volume' in the '...then', it will say the response only once. As soon as the 'Set volume' is added, the response comes twice.
![flow2](https://cloud.githubusercontent.com/assets/11725674/13471320/5638162e-e0b0-11e5-95aa-a38c8cb0dad8.png)

**What was the result?**

All of a sudden another flow gets executed twice.

**What did you expect as result?**

That adding a 'Set volume' action impact has no impact on triggers.

**Any other remarks**

Logging from the OpenTherm Gateway app shows that the trigger to send a command (is Flow 1) is triggered twice when the 'Set volume' is added to Flow 2.

> 19:41:18.183 Received sendCommand action trigger
> 19:41:18.185 Sent command PR=A
> 19:41:18.185 Updating value of CommandResponse to 
> 19:41:18.186 Calling function for response
> 19:41:18.230 Updating value of CommandResponse to PR: A=OpenTherm Gateway 4.2.3
> 19:41:18.230 Calling function for response
> 19:41:18.231 Sending trigger 'command' with value OpenTherm Gateway 4.2.3
> 19:41:19.032 Received sendCommand action trigger
> 19:41:19.033 Sent command PR=A
> 19:41:19.034 Updating value of CommandResponse to 
> 19:41:19.035 Calling function for response
> 19:41:19.078 Updating value of CommandResponse to PR: A=OpenTherm Gateway 4.2.3
> 19:41:19.078 Calling function for response
> 19:41:19.079 Sending trigger 'command' with value OpenTherm Gateway 4.2.3

**Comment by WeeJeWel** [comment]
I'm pretty confident that the Wallswitch fired twice. @Dennishacq I am experience similar results sometimes.

**Comment by nlrb** [comment]
Let me try with an NFC tag as trigger tonight and I'll report back. That should confirm whether it is a KAKU issue.

**Comment by nlrb** [comment]
Replaced KAKU switch trigger with an NFC tag trigger and the problem goes away. So indeed looks KAKU related.

**Comment by MdeRhoter** [comment]
Has the root cause of this ever been found? I seem to have a similar issue with flows occasionally running twice when triggered once. With and without Kaku triggers.

**Comment by WeeJeWel** [comment]
KaKu sometimes fires twice, it's extremely hard to filter for duplicate signals. @Dennishacq is adding a debouncer.

**Comment by ralfvd** [comment]
In 0.8.32 , 433 (Kaku and other devices) command sent by a remote are processed 4-5 times. If I press a button on a Kaku (or Action) remote, the associated flow gets executed 4-5 times, with a delay of 1-2 seconds in between. 

At 0.8.30 this was not an issue.

**Comment by Dennishacq** [comment]
I just released version 1.1.12 of the KaKu app.
This version includes a new debouncer that should fix this problem. Let me know if this fixes your issue!

**Comment by Dijker** [comment]
Thanks! I tested it with a flow pushing msg to my mobile, Looks good. Tested several times (approx 20 pushes) with the Doobell ACDB-7000A and just a button on AYCT-102. 
Not one trigered more than once. only when pushing really fast (within 2 seconds?) it didn't trigger. 

But that is expected as KAKU/433 features some reliability by retransmiting this slow signal 

as we say:  for every disadvantage there is an advantage ;-)

**Comment by ralfvd** [comment]
Still the same issue with AYCT-102 : flows triggered by a remote button get
executed multiple-times. It also takes 1-2 seconds before the flow is
executed.

**Comment by freemann** [comment]
Few days ago I bought 2 AYCT-102 remotes and both work like a charm.
1.1 on/off is used for switching all Livingroom HUE's and that works great within 1-2 secs the all go on/off

remote 2;
2.1 switching a 433 through Homey (button on is received by Homey and Homey sends command to 433 Elro unit)
2.3 is used for switching the bedroom HUE Bloom to a soft red tone
2.4 is used for switching the bedroom HUE Bloom to a bright white tone

All works fast and reliable.

**Comment by ralfvd** [comment]
Marco,

If I use them 'one-way' ( so button 1 ON -> light ON ), there is no issue
when commands are sent multiple times. But e.g. I use the remote to start a
radio (and announce starting via the Homey speaker). Then I hear 3-4 times
"Starting radio".

Could you include in one of the flows a "Say Something" flow? And see if
you get this triggered multiple times?

Thanks,

Ralf

**Comment by freemann** [comment]
Could you post a example/screenshot of that flow, then I will make the same flow for testing.

**Comment by ralfvd** [comment]
![screen shot 2016-04-30 at 11 55 47](https://cloud.githubusercontent.com/assets/17275712/14935237/8ed915a8-0eca-11e6-9e75-42848f223e23.png)

So, trigger is one of the remote buttons. Action is then (in my case issuing a HTTP GEt command to start the radio) and a Speaker 'say something' card to announce starting the radio

**Comment by Dennishacq** [comment]
@ralfvd
Does your flow also trigger multiple times when you remove the http get action?

**Comment by freemann** [comment]
OK! 

Tried it right away;
![screenshot - 30-4-2016 11_56_11](https://cloud.githubusercontent.com/assets/601053/14935241/cf1334c8-0eca-11e6-9354-ada406984158.png)

I used the AYCT-102, button 4 ON and Voice card.
Tried to push the button one(!) time for several times with 5-10 secs between the pushes and Homey every time only says one time "Hi!"
Tried to push several (2-3) times within 1 sec and then Homey also says 1 time "Hi!"
Tried to push several (2-4) times within 2-4 secs and then sometimes Homey says "Hi!" for 2-3 times.

**Comment by ralfvd** [comment]
@Dennishacq I  removed the http GET card, but no difference; Homey still says 'Starting Disney radio' 4 times. The webinterface of Homey feels a bit sluggish at the same time, so maybe that's related. This is immediately after a reboot. Logfile: 9E0B8A606D

**Comment by freemann** [comment]
OK, my Homey also shows this strange behavior....

The only thing i change for the last 24h where;
1. install the pushover app
2. remove the acdb7000ac doorbell and install the acdb6600ac doorbell

When i press the adcb7000ac sender, the KAKU doorbell rings once and the Dumpert Anthem sounds multiple (sometimes 2-4) times at a time.

**Comment by Dennishacq** [comment]
@freemann 
Are you still experiencing this issue with KaKu v1.1.3?

**Comment by freemann** [comment]
nope, from my perspective this is solved :+1:

**Comment by nlrb** [comment]
Issue still exists with v1.1.3 & fw 0.8.36.

**Comment by Dennishacq** [comment]
@nlrb is it still the same flow as you posted before? Does this also happen when you make a flow that makes Homey say something when you press your wallswitch?

**Comment by nlrb** [comment]
Used this flow now:
![image](https://cloud.githubusercontent.com/assets/11725674/15907749/ab81d68c-2dbe-11e6-962b-47a773e7e966.png)
As a response I get 'Ola Ola Ola', 'Got OpenTherm Gateway 4.2.3' (3x), 'Ola Ola Ola'. 'Got OpenTherm Gateway 4.2.3' (2x) 'Ola Ola Ola' 'Got OpenTherm Gateway 4.2.3' (2x) 'Ola Ola Ola', 'Got OpenTherm Gateway 4.2.3' (2x)
Just pressed the button once...
(The 'Got OpenTherm Gateway 4.2.3' is the response to the 'PR=A' command)

**Comment by Dijker** [comment]
I don't see the volume device or two step flow triggering another flow  in your last example anymore.
I guess we are only bug hunting the KAKU debouncer from now.

Just a silly question,
Do you have a range extender for KAKU like the AEX-701 
http://www.klikaanklikuit.nl/shop/nl/signaalversterker-aex-701/

And can you simplify the flow to:
On: button pressed
Then: increment a better logic variable.

You can view updating the value of the variable at the Better Logic dashboard 
If you press the button with an interval of at least 10 seconds you can view if the value increases one or more every button press eliminating all other flow cards you are using now.
Just my 2 ct.

**Comment by ralfvd** [comment]
I also have this issue back ( 0.8.38 + Kaku 1.1.6 ) . When pressing the
Kaku remote button, the corresponding flow is -after a delay of 1-5
seconds) started 4-5 times.

It was good for a while ( or only an occasional 2 time triggering of a
flow).

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by nlrb** [comment]
Still multiple triggers with Kaku v2.0.6.

**Comment by BasKiers** [comment]
I cannot reproduce this issue, I think that if this issue still persists it lies with the Opentherm app (https://github.com/nlrb/com.tclcode.otgw). Could you test if the second flow still triggers twice when you click the 'Test' button in the first flow

**Comment by nlrb** [comment]
It is indeed hard to reproduce nowadays with FW 0.9.3 and kaku 2.2.1. Have only had it once in ~25 tries that the flow got executed twice. So the current debouncer looks to work well.
It is definitely not the OTG app; don't know why you would suggest that. That doesn't make any sense at all.
It never fires more than once with the test button (it never has).
