### ISSUE TITLE
Aeotec Z-Wave Smart Switch 6, Gen5 

### ISSUE THREAD

**Issue by mruiter** [athombv/homey#324]
**What is your Homey version (Settings → System)?**

0.8.82

**What did you try to achieve?**

Z-Wave Pair on with the Aeotec Z-Wave Smart Switch 6, Gen5 

**What was the result?**

Interviewing failed. The message box : You are able to switch the device on/off

**What did you expect as result?**

Device got added. Is available as a device in devices. When you try to switch the graphical representation of the switch does not flip. Nothing happends on the Aeotec Z-Wave Smart Switch 6
Also it's not possible to give Z-Wave configuration data because the boxes are missing.
Power Usage function to monitor also not detected.

Deleting the device crashes homey.

**Comment by ocatie** [comment]
Fixed in 0.8.23

If a device failed the interview a socket is added so the device can be interacted with using Basic Set commands.

**Comment by mruiter** [comment]
Not fixed. Same error same crashes . Log send under FB87AD74A7

**Comment by mruiter** [comment]
Look @ocatie i already said it was not fixed.

**Comment by ocatie** [comment]
Sorry, I missed your previous comment. Will take a look at the log. Thanks for mentioning.

**Comment by jstranders** [comment]
Same or very similar issue appears with Aeotec's Multisensor Gen5. Can only be paired as a 'generic' on/off device.

**Comment by ocatie** [comment]
It seems during the interview a frame dropped. Can you try again with the device close to Homey? Within 2 meters.

**Comment by jstranders** [comment]
hi Taco,

I already tried a dozen of times when distance between Homey and
multisensor was < 30 cm.
I'm on 0.8.29 firmware, by the way.

Do you want me to try again?

Best,
Jonathan

2016-04-11 14:01 GMT+02:00 Taco <notifications@github.com>:

**Comment by freemann** [comment]
Try is multiple times and after each time create/send a Log file.

**Comment by ocatie** [comment]
If you could remove the device, reboot Homey, add the device and send the log it would be very helpful. In the log I might find the cause of the interview failing.

**Comment by thezahir1** [comment]
@ocatie "Oops, I did it again..." Here's my log ID 'C356EF8CB0'. Distance Homey / Sensor was 5 cm this time.
I'm close to my Airport Express router. Could that cause interference problems?

**Comment by thezahir1** [comment]
@ocatie Any update already on this?

**Comment by ocatie** [comment]
Not yet

**Comment by thezahir1** [comment]
@ocatie any expectation on when the sensor will work? Cause currently I am really waiting for my Aeon multisensor to work in order to create some flows that are really relevant to me (e.g. lowering sun curtains when indoor temperature + light exceed some treshold levels).
Any status would be very welcome.

**Comment by freemann** [comment]
Most people here are waiting..... some more then 2 years..... a bit more patience would be helpful :smiley:

**Comment by thezahir1** [comment]
@freemann Yes Marco I know. I am one of those people too... ;)

**Comment by mruiter** [comment]
Looks like a fix did not make it in .30
Still failing. :(

**Comment by mruiter** [comment]
Oeps, pushed the wrong button

**Comment by thezahir1** [comment]
@ocatie Eagerly waiting. Is there an update and/or expectation when this and other z-wave devices will be working again?

**Comment by thezahir1** [comment]
@ocatie Are you having a holiday these weeks or just not bothering to keep us updated?
I would very much get the Aeotec sensor working because a lot of my flows will be depending on luminance, temperature etc. So I seriously call upon you to get a proper feedback ;)

**Comment by ocatie** [comment]
Do you mean the multisensor or the smartswitch? If you experience the same error it would help me if you could send a log. Would be appreciated :)

**Comment by thezahir1** [comment]
It's the sensor. Any updates on that front?

**Comment by mruiter** [comment]
@thezahir1  Sensor is working , look for settings in the forum in the devices section. 
@ocatie would you like a new log with the smartswitch added and a non working switch with slider 0 to 100% ?

**Comment by thezahir1** [comment]
Okay thanks @mruiter. I didn't see that yet. The thing is, I haven't activated experimental releases,so I'm still on 0.8.29.
Dunno what plagues will hit me when moving from stable to experimental. 
Is it, by the way, possible to go back to stable once you've gone to experimental?

**Comment by ocatie** [comment]
@mruiter Could you send a log on 0.8.32?

**Comment by daneedk** [comment]
@thezahir1 
You need to be on 0.8.32 to get it to work:

https://forum.athom.com/discussion/1329/how-to-aeotec-multisensor-6#latest

In order to not get newer experimental after the first experimental you have to reset your homey, that will take you off the experimental track but will not restore to a stable version.
Roll back is not possible, you will be on experimental until there is a new stable.
https://forum.athom.com/discussion/1159/why-wont-an-experimental-build-be-rolled-back-to-stable-when-i-reset-my-homey#latest

**Comment by thezahir1** [comment]
Thanks @DaneeDk. So reset does not mean losing all of your settings/flows/apps, right? Only a reboot so to speak? (I hope)

**Comment by daneedk** [comment]
If I remember correctly you get asked if you want to keep your data and relink it to your Athom account. I cleared it completely to start all over again. Took some time to reconfigure everything all over but that way you are sure you make a clean start.

**Comment by thezahir1** [comment]
Hi @daneedk I did what you suggested and first went on the experimental bandwagon. After going to 8.0.32 and doing a subsequent reset (with keeping the user data) i wanted to disable experimental updates, but the checkbox is greyed out, so impossible to disable.
Any idea how I can disable it now?

**Comment by mruiter** [comment]
@ocatie 
Finaly had the time for the logs file.

There are two. First was when i did a clean power remove and on and zwave was completely down. Reset zwave chip did not help.
Second is when the switch was added.

28CA38A97E		after reboot zwave not functional also not with zwave chip reset

21AB6A4614		after adding aeotec smart switch as device but not able to switch. No power reading and a slider like its a dimmer which its not

**Comment by mruiter** [comment]
Confirmed as still the same. Not working on .34 and a dimmer slider that should not be there

**Comment by ocatie** [comment]
The switch supports the Multilevel Switch command class. Thats why the dim capability is assigned. If the device cannot be controlled with this command class, it will be fixed with an app.

**Comment by mruiter** [comment]
but on/off switch also does not do anything. 

The slider being there and doing nothing is no problem for us :)


Outlook voor Android






On Tue, May 17, 2016 at 6:05 AM -0700, "Taco" <notifications@github.com> wrote:












The switch supports the Multilevel Switch command class. Thats why the dim capability is assigned. If the device cannot be controlled with this command class, it will be fixed with an app.

**Comment by ocatie** [comment]
On/off commands are also send with the Multilevel Switch command class if supported.

**Comment by rbusscher** [comment]
no progress with 0.8.35. Still no working Smart Switch 6. 
![screenshot_5](https://cloud.githubusercontent.com/assets/19496411/15440044/8d298152-1ed3-11e6-86e0-ca4ed1d5ce04.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/19496411/15440045/8d2b2a16-1ed3-11e6-9fcc-1dd8fc4acdd4.png)

**Comment by mruiter** [comment]
confirmed. still useless

Verstuurd vanaf mijn iPad

**Comment by rbusscher** [comment]
Is this solved with the rewrite of the zwave?

**Comment by mruiter** [comment]
should be. that's what's the rewrite is for


Outlook voor Android






On Sat, Jun 11, 2016 at 10:47 AM +0200, "rbusscher" <notifications@github.com> wrote:












Is this solved with the rewrite of the zwave?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
