### ISSUE TITLE
Homey does not try to reconnect to WiFi

### ISSUE THREAD

**Issue by zperx** [athombv/homey#516]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Leave Homey alone to do what it needs to do and to be connected and accessible.

**What was the result?**

Homey looses the the connection what is not an undocumented issue but this one is about the reconnection. Homey does not try to reconnect to the WiFi router (or if it does it is never successful). The only way to make him try to reconnect is by a hard restart (by unplugging the cable).

**What did you expect as result?**

A connected device. Automatic reconnection in the case of a lost connection.

**Any other remarks**

My router is very reliable so as my ISP. None of my devices ever had any connectivity issue.

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.32.

**Comment by zperx** [comment]
So far so good. WiFi connection is still not reliable but at least it seems to reconnect every time.
