### ISSUE TITLE
DNS servers are hardcoded

### ISSUE THREAD

**Issue by mtudor** [athombv/homey#518]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

In an app, resolve an address "media.mydomain.com" which is manually set to resolve in my _local_ DNS server settings.

*Please include detailed steps how we can reproduce the issue*

Create an app that attempts to connect to a DNS address that is mapped on a local DNS server.  Alternatively, a ping from the SSH console will probably show the same effect!

**What was the result?**

Cannot resolve the DNS name to IP address (ECONNREFUSED)

**What did you expect as result?**

Correctly resolved the address (e.g. media.mydomain.com) to IP (e.g. 192.168.0.100).

**Any other remarks**

It seems like Homey may be hardcoded to use Google DNS servers rather than those specified in local DNS.  This is an issue in circumstances like those above and Homey should really use the DNS servers specified in the router / local dhcp server.
 - https://forum.athom.com/discussion/1074/homey-doesnt-want-to-connect-to-airport-extreme/p1
 - https://forum.athom.com/discussion/1255/does-homey-block-outgoing-http-requests-on-non-standard-ports

**Comment by WeeJeWel** [comment]
Fixed in 0.8.33

**Comment by RoadXY** [comment]
But Homey still can't resolve my internal Exchange server on 0.8.34 ?

**Comment by WeeJeWel** [comment]
I'll investigate :-)

**Comment by RoadXY** [comment]
Tried again in 0.8.39 en still doesn't use the DNS provided by the DHCP server...

**Comment by WeeJeWel** [comment]
@jeroenvollenbrock can you investigate?

**Comment by jeroenvollenbrock** [comment]
Found a bug in the DHCP configuration causing Homey to ignore every name server entry except the first listed entry (google DNS). Fixed the bug and changed priorities. Homey is now configured to use google DNS as fallback if-and-only-if the DHCP issued DNS config cannot resolve a query. (@weejewel: fix is staged for the next production build). Please note that if a unicast .local domain exists, avahi now gets disabled to resolve conflicts.
