### ISSUE TITLE
Unable to select different voice

### ISSUE THREAD

**Issue by elgenioNL** [athombv/homey#53]
- Downloaded voice Emma > select it > voice is now British female.
- Downloaded voice Sally > select it > no sound.
- Selecting voice Brian> voice stays Emma. Error in console:
 
> PUT http://192.168.1.57/api/manager/speech-output/settings/?_=1455130769874 500 (Internal Server Error)
> Uncaught SyntaxError: Unexpected token E

- After power cycle > no voice whatever is select.
- Select voice Emma > power cycle > Voice is Emma again.

I have done the same thing 2 times to verify the problem
Question to Homey to test voice: "what's the time"

**Comment by WeeJeWel** [comment]
Now that is a bug report! Luckily this issue is already fixed in 0.8.17 :-)

**Comment by elgenioNL** [comment]
Confirmed fixed on downloaded voices.

Still unable to select Brian, error in console:

> PUT http://192.168.1.57/api/manager/speech-output/settings/?_=1455133283404 500 (Internal Server Error)

**Comment by WeeJeWel** [comment]
Could you click that link in the console, select the 'Response' tab and make a screenshot?

**Comment by elgenioNL** [comment]
> {"status":500,"result":"Unable to load voice:/opt/user/manager/speech-output/voices/en-gb-brian/vox.so: cannot open shared object file: No such file or directory"}

**Comment by WeeJeWel** [comment]
OK thanks!  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl
