### ISSUE TITLE
Missing wlan0 network interface

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#591]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**
Retrieve local IP offline

*Please include detailed steps how we can reproduce the issue*
https://github.com/matjaz/homey-better-presence/blob/1d752b5eaeec637ba814c11e396e9d77dc14cb36/app.js#L94

**What was the result?**
Crash report
TypeError: Cannot read property 'filter' of undefined at getLocalIP (/app.js:94:42)

**What did you expect as result?**
wlan0 to be present.

**Any other remarks**
I know there is async version to get local IP, but having offline version is more reliable and IMHO wlan0 should be always available.

**Comment by WeeJeWel** [comment]
This is not available due to security restrictions of the app sandbox.

The API call is also offline, yet it's asynchronous because it communicates with Homey core. In the end, the same os.networkInterfaces() is called ;-)

**Comment by matjaz** [comment]
Interesting part is it works for most users. But it looks it crashes for some..

**Comment by WeeJeWel** [comment]
That can happen when the library is needed during app bootstrapping.

**Comment by matjaz** [comment]
Don't quite understand what do you mean. AFAIK chroot doesn't interfere with network interfaces.

**Comment by WeeJeWel** [comment]
It does with node.js loading required libraries! For example, I got to make a 'fake' dns request, otherwise the dns library isn't loaded.

Node.js + chroot = fun ;)

**Comment by matjaz** [comment]
aha. in .34 you control `require` :)

**Comment by matjaz** [comment]
Did you consider using containers?

**Comment by matjaz** [comment]
Looks like `require` overriding broke a lot of things..
#600 #602 #603 #604
https://athomcommunity.slack.com/archives/developers/p1463220104000803

IMO removing core node modules will cripple apps.
I understand removing network interfaces if we have Homey API for that, but removing general like `EventEmmiter` is not good direction. It will hurt apps.
I am more for black-listing calls that can expose Homey internals.

**Comment by Joolee** [comment]
EventEmitter is not removed, I just forgot to require it. The problem was/is that the error is looping indefinitely.

**Comment by matjaz** [comment]
Aha. If I understand correctly in .34 you removed `require` after `init()`. That's what `console.log(Object.keys(global))` tells me. :)

**Comment by WeeJeWel** [comment]
I didn't touch require at all. I'll look into it...

**Comment by nattlip** [comment]
i tried EventEmitter in my code a few weeks ago but i got strange results , so i stopped with it. homey code uses a lot of disguised EventEmitters. Is the Eventemitter not affted by that ?.

**Comment by matjaz** [comment]
I get `ReferenceError: require is not defined` after app's `init` finishes.

**Comment by WeeJeWel** [comment]
O.o

OK, will look into it

**Comment by WeeJeWel** [comment]
Can you provide a bare code example, so I'm sure I can reproduce?

**Comment by matjaz** [comment]
app.js
```
'use strict'

exports.require = require

exports.init = function () {
	Homey.log('Hello world!')
}

exports.uptime = function () {
    const uptime = require('os').uptime()
    console.log(uptime)
    return uptime
}
```

api.js
```
module.exports = [{
    description:    'debug',
    method:         'GET',
    path:           '/debug',
    fn: function(callback, args){
        callback(null, new Function('args', args.query.body)(args))
    }
}, {
    description:    'uptime',
    method:         'GET',
    path:           '/uptime',
    fn: function(callback, args){
        callback(null, Homey.app.uptime())
    }
}]
```

works
`api('GET', '/app/dev.require/uptime')`

gives `undefined`
`api('GET', '/app/dev.require/debug?body=console.log(global.require)')`

triggers forever loop
`api('GET', '/app/dev.require/debug?body=console.log(require("os"))')`

works
`api('GET', '/app/dev.require/debug?body=console.log(Homey.app.require("os"))')`

strangely this all worked in .32

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35.

**Comment by matjaz** [comment]
just received same error from 0.8.35.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by matjaz** [comment]
haven't seen it in a while. you can close it.
