### ISSUE TITLE
Somfy blinds not working after update to 0.8.34

### ISSUE THREAD

**Issue by dhanstede** [athombv/homey#596]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**

Try to get the somfy blinds down, or to pull up the somfy blinds

*Please include detailed steps how we can reproduce the issue*

After update to 0.8.34 it's not working. i have powercycle homey, but no result. de-install and install the app; no result. After this i have re-add the somfy blinds. Adding looks oke, the blinds are shaking. But after that no response when i am press the up or down buttons.

**What was the result?**

Nothing.

**What did you expect as result?**

The blinds are going down or up

**Any other remarks**

No

...

**Comment by nattlip** [comment]
me to

**Comment by Inversion-NL** [comment]
Yup, also not working here while .28 and .32 it did work

**Comment by jaxc0402** [comment]
+1

**Comment by BasPost** [comment]
Yup, not working anymore here

**Comment by markmg** [comment]
same here only my blinds are not reactiing on anything.
when adding i get zero movement

**Comment by Dennishacq** [comment]
Hi guys,
I have found the bug and it is fixed in Somfy v1.0.12 which should be in the appstore later this week.

**Comment by Dennishacq** [comment]
Somfy v1.0.12 is now available in the appstore

**Comment by markmg** [comment]
Still not working for me 
tried to reinstall, remove, install reboot, power cycly 
noting, no reaction at all

**Comment by RoadXY** [comment]
Did you verify you have v1.0.12?
Because Homey only update's every 6 hours.

**Comment by markmg** [comment]
yeah i am sure its 1.0.12 installed it from the app store
managed to get 1 blind working now but it only responds for 2 seconds

**Comment by RoadXY** [comment]
Ok.
What do you mean by responds for 2 seconds?
It has an delay of 2 seconds after each command?

**Comment by BasPost** [comment]
Hi, I just did "install" from the app store, no reboot or uninstalling then old app.
And my 2 Somfy blinds are working again. Even the "my" button works!
Thanks for fixing the issue

**Comment by markmg** [comment]
its the same problem i had before with responding only for 2 seconds 
https://github.com/athombv/homey/issues/565

But only 1 blind the other 3 blinds are not pairing at all

**Comment by RoadXY** [comment]
@markmg 
Strange because the signal is only send once, after that the motor should keep moving until it's at it's programmed end/begin.
Did you ever use any other 3rd party software successfully with your Somfy blinds?
Like Domoticz or any other?

**Comment by markmg** [comment]
yeah its strange, i never used 3rd party software only the original Somfy Telis 4 remote witch works perfect for the rest no problems what so ever.
Thats the only reason i bought a Homey to control my blinds :) 

i am a step further, if i pair without the Telis 4 remote i am able to add another blind, i pressed the connect button on the RTS its self, blind but still the same problem it responds for 2 seconds then stops

**Comment by Deentje** [comment]
The issue with somfy is also fixed for me with the update to 1.0.12. Thanks !!

**Comment by RoadXY** [comment]
Somfy is working again, thanks!

**Comment by dhanstede** [comment]
After the update my somfy blinds are working again! thanks

**Comment by nattlip** [comment]
needless to say it works again

**Comment by markmg** [comment]
Same here got them working, 

still have the problem the only respond for 2 seconds, they MY button dos work and opens the blinds all the way

**Comment by Dennishacq** [comment]
@markmg I have just released v1.0.13 of the Somfy app which sends the signal with a smaller amount of repetitions. Let me know if this fixes the problem :)

**Comment by glijie** [comment]
Ik have 4 blinds and 2 of them have still the problem they only respond for 2 seconds, they MY button works.

The other 2 works perfect. 
I have 2 same rts remotes one for the attic wicht works...and one for livingroom which only workshop for 2 sec.

**Comment by Dennishacq** [comment]
@glijie What Somfy motors do you have?

**Comment by glijie** [comment]
For the two wich are not fully working. 

Tilt&lift 25 RTS Central somfy motor

**Comment by Dennishacq** [comment]
@glijie I think your blinds are in installing mode. Check the manual to exit this mode.
Manual can be found at: http://www.oceanair.co.uk/commercial/sites/oceanair.co.uk.commercial/files/technical-documents/TILT%26LIFT%2025%20RTS%20-%20manual%20English.pdf

**Comment by glijie** [comment]
Ik wonder why you think that the blinds are in installing mode? The remote for two blinds is working fine. And i use them with Homewizard without any issues? 

Ik have checked  the mannual and i think indeed that everthing is working as supposed. In the mannual is not spoken over how to exit installing mode


Patrick

**Comment by Dennishacq** [comment]
> I have 2 same rts remotes one for the attic wich works...and one for livingroom which only works for 2 sec.

I thought you meant that your blinds also react for two seconds when you are using your remote. Is this not the case?

**Comment by glijie** [comment]
No when ik use the remote everthing works fine...only when ik use homey to open or close the blinds in living room , the blinds move for a second and than stops. The MY position with use of homey Does works good.

The blinds on the attic works great with homey.

Patrick

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by dhanstede** [comment]
Also after updating to firmware 0.9.2. my somfy blinds still working fine!

I will close this issue.

**Comment by glijie** [comment]
2 day's ago before i left on holliday,  i had the same problem like before.
