### ISSUE TITLE
KaKu Flow's are dead.

### ISSUE THREAD

**Issue by posthok** [athombv/homey#682]
**What is your Homey version (Settings → System)?**

0.8.38

**What did you try to achieve?**
Nothing, only working flows

*Please include detailed steps how we can reproduce the issue*
after updating to 8.38 flows aren't working anymore.
Devices work when i trigger them in devices, but the flows don't trigger anything anymore.

**What was the result?**
a fully non functional Homey
...

**What did you expect as result?**
A working device
...

**Any other remarks**
I have did a reboot. Power off and on. Turned off kaku and on again. Deleted KaKu rebooted and reinstalled but no result.

...

**Comment by djeskoswe** [comment]
Same here,  all Kaku devices are dead..

**Comment by Arjanvde** [comment]
Did you try a cold reboot (remove power for 30 seconds), fixed the issue in my case.

**Comment by djeskoswe** [comment]
Cold reboot did the trick to add new units,  but no go in flow!

**Comment by posthok** [comment]
did a cold start too. Flows are still dead

**Comment by djeskoswe** [comment]
When using 433 wallswitch the flow triggers but with 433 remote or zwave socket hardware on/off no flow triggers.

**Comment by Dijker** [comment]
Very strange, 
- 4 testflows that react on a KAKU button (Doorbell, AWST8802 , AYCT-2102) ALL still work after updating to 0.8.38 (Pulse Ring, increment Better Logic value )
- tested two functional flows, one with a KAKU door contact disabling the thermosmart and one other  AWST8802 triggering the start of KAKU ASUN650 screen. Both dead as you mentioned. 
But still possible to test the flow to move the KAKU ASUN650  screen, it works and the flows (4) for the doorcontact also work 

Send Logs:
5FD83A3CBF

**Comment by posthok** [comment]
all flows working with the test button. That's also the only way to trigger.

**Comment by posthok** [comment]
Just made a timer flow and let homey say the time. This trigger worked.
Seems Kaku related.

**Comment by bvdbos** [comment]
door sensor AMST606 can be added but it doesn't work in flows. 
remote AYCT102 remote can be added and does work in flows.
remote APA3-1500R can be added but doesn't work in flows (but other reason: channel 0 can't be selected in the trigger-column)

**Comment by glijie** [comment]
sensor AMST606  stopt working,
Kaku motion sensor stopt working
and the virtual buttons (sockets) stopt working.

therefore most flows i use stopt working.

Kaku which added with a remote signal are working

**Comment by posthok** [comment]
tried the doorbell as well and indees the doorbell does his job. Strange

**Comment by bvdbos** [comment]
Which switch and which doorbell?

**Comment by posthok** [comment]
![homey doorbell](https://cloud.githubusercontent.com/assets/6661318/15985000/76d1aabc-2fde-11e6-8c13-5d9115f1f848.jpeg)
Kaku doorbell

**Comment by posthok** [comment]
i did a little experiment with a flow. Added the same kaku doorsensor (which not worked in a flow) to homey but now with the smartwares app . And now this doorsensor works in a flow.
Doorsensor open lights on. Doorsensor closed lights off.
It seems some kaku signals don't come trhought in the if section.

**Comment by posthok** [comment]
And her's another or maybe the same issue.
![homey insights](https://cloud.githubusercontent.com/assets/6661318/15986113/f9e1e25c-2fff-11e6-9715-876a8fd67a34.jpeg)
This picture shows only a couple of my device's

![homey flow devices](https://cloud.githubusercontent.com/assets/6661318/15986122/35c881c2-3000-11e6-802c-6027b0a17ea2.jpeg)
but on the left are all my devices

**Comment by bvdbos** [comment]
The devices which can't be used as a trigger are the same devices which don't show in insights?

**Comment by MdeRhoter** [comment]
Just to chime in here, I have what looks like the same issue.

My repro:

Single AWST-6000 motion detector, used in a flow to change a variable.
In the Devices section I can see that it detects motion (on motion, it switches on, then off, as it should)

However, the variable in the flow doesn't change, because the flow doesn't trigger.

Other KaKu devices that do trigger a flow successfully: 

- AYCT-102 remote control
- ACDB-7000BC doorbell

So it doesn't seem to affect *all* KaKu transmitters, just some. Rebooting, cold or otherwise, doesn't help. Neither does re-adding the devices.

**Comment by Dijker** [comment]
@MdeRhoter 
It is the same I see. Some work some don't

**Comment by bvdbos** [comment]
For me this also (seems to) happen with a bitflip device. On the forum Djesko claims also zwave experiences this. Timer does trigger, some Kaku's do trigger. Dijker, you are sure the AWST8802 does trigger in certain flows and doesn't trigger in other? Do the triggers show up in the log ofr you all?

**Comment by Dijker** [comment]
Yes, 
I have two AWST8802, the one that is installed triggers a nonexistent virtual socket in Homey normal to let the asun650 SunScreen go 26 seconds down. This one doesn't work any more . So it is the socket defined in the flow.
The other on my desk counts to test the KAKU debouncer and still works,  a better logic value increase with every button pressed.
The motion sensor and contact sensor both also stopped working.
I replaced the contact sensor with the AWST8802 button for the time being.
The doorbell still works.

**Comment by bvdbos** [comment]
Ah, that explains it. The AWST8802 works as it should but the virtual socket doesn't. I have a virtual socket too which doesn't work. Contact-sensor AMST606 also? I don't know if there's multiple motion-sensors but do you know which typenumber this is?

**Comment by Dijker** [comment]
@posthok 
As strange my contact sensor amst606 from KAKU stopped also, I could re-add it but stop no flow that triggers. I could also add it has a smart wares  learning is still ok and the working is verified opening the device card. But still no trigger, it doesn't work for me :(

**Comment by MdeRhoter** [comment]
It would be useful to find out if this worked in versions older than 0.8.38 - if anyone can test this, please do! It may just be the Kaku-app, since that also got bumped a few times recently.

**Comment by posthok** [comment]
@bvdbos Yes the contact sensor showed in insides is the only trigger that worked

**Comment by matjaz** [comment]
I experience same behaviour with Aldi app on .38.

**Comment by posthok** [comment]
Turned off alls apps. Did a reboot, turned on all apps. Now all devices in insides are gone,

**Comment by glijie** [comment]
@MdeRhoter on 08.36 everything worked just fine after update 0.8.38 some kaku stopt working.

**Comment by jordenc** [comment]
Same here with the doorbell.

**Comment by freemann** [comment]
KaKu acdb-6600ac & AYCT-102 are working really great here!

**Comment by Dennishacq** [comment]
Hi guys, 
I just released an update for the KaKu and Aldi app which should fix this issue.
Please let me know if it works!

**Comment by bvdbos** [comment]
The devices are showing up in insights and using a socket as trigger for sending a message works for me now... :+1:

**Comment by glijie** [comment]
Everything works again heren....Thx

**Comment by djeskoswe** [comment]
thanks

**Comment by MdeRhoter** [comment]
Motion Detector AWST-6000 works - thanks @Dennishacq!

**Comment by Marc1979** [comment]
Here no Kaku works after update. Only test works while add an device

**Comment by bvdbos** [comment]
I tried this from work at first, didn't see my lights weren't going on. On/Off doesn't work for me but dimmer works. On/Off doesn't work in a flow either...

**Comment by MdeRhoter** [comment]
Kaku sockets are indeed dead here as well. Motion sensor works though, so there's that :)

**Comment by bvdbos** [comment]
receiving works, sending works partially?

**Comment by MdeRhoter** [comment]
Looks like it. Win some, lose some! @Dennishacq - could you take a look?

**Comment by posthok** [comment]
Dusk sensor (schemerschakelaar) and doorcontact sensors still don't work.

**Comment by MdeRhoter** [comment]
Changing the brightness of a dimmable Kaku socket in the Devices section does work. A dimmable socket does can't be switched on or off though.

**Comment by bvdbos** [comment]
doorcontact works for me...

**Comment by posthok** [comment]
@bvdbos In a flow in the if section?
if door open lights on?

**Comment by posthok** [comment]
![homey sfeerlicht](https://cloud.githubusercontent.com/assets/6661318/16060178/c59c1998-3286-11e6-94f6-5d6dc32fc1a2.jpeg)
This flow is working. Homey said: "sfeerlicht aan". but the lightslevel does not change.

![homey open door](https://cloud.githubusercontent.com/assets/6661318/16060247/16dd60e6-3287-11e6-829c-d777ca99fbdb.jpeg)

In devices i'll see the door getting open but the flow won't trigger.

**Comment by BasPost** [comment]
All my KaKu modules stopped working after the update 1.1.4 on 0.8.38 last night. I can't send any on/off commands.
Everything worked fine before update. I disabled and enabled the app, reboot and powercycle, but issue remains

**Comment by glijie** [comment]
only the sockets which where added with a remote control from kaku stopped working.
all other kaku works overhere.

**Comment by jordenc** [comment]
I still can't pair the doorbell ACDB-7000AC

It worked before the 0.8.37 / 0.8.38 update

**Comment by jordenc** [comment]
Update: I pulled the plug on Homey and then booted it up. Afterwards I was able to pair.

**Comment by posthok** [comment]
Kaku is now completely dead. does'nt work anymore

**Comment by Dennishacq** [comment]
I updated KaKu to 1.1.5 which should solve the issues.

@posthok Repairing your device should fix this error.

**Comment by posthok** [comment]
Thanx Will try

**Comment by caseda** [comment]
I'm getting the same error as @posthok with the app crashing.

It only happens when you activate a flow with the door sensor in it (either as trigger or as "AND" capability)
You can still see the status of the sensor in the mobile card before it is crashing, so it is just a trigger/status problem.

It start with a smaller error:

> Stack trace:
> 
> TypeError: Cannot read property 'variables' of undefined
> at Object.module.exports.self.capabilities.alarm_contact.get (/drivers/switch/driver.js:129:28)
> at Object.<anonymous> (/drivers/switch/flows.js:51:39)
> at emitThree (events.js:102:20)
> at Object.emit (events.js:175:7)
> at /homey-app/manager/flow.js:1:194
> at /homey-app/helpers/client.js:1:868
> at Array.forEach (native)
> at process.<anonymous> (/homey-app/helpers/client.js:1:835)
> at emitTwo (events.js:87:13)
> at process.emit (events.js:172:7)

But in time it generates the error @posthok is showing.

This includes in app version 1.1.5 (@ Homey FW 0.8.38)
Cold (few minutes) boot doesn't help.
Readding (all) sensor's doesn't work.
Reinstalling doen't work.

**Comment by posthok** [comment]
@caseda: Can confirm this 
Kaku App 1.15 Still brings no solution.
Stack trace:

TypeError: Cannot read property 'variables' of undefined
at Object.module.exports.self.capabilities.alarm_night.get (/drivers/switch/driver.js:123:28)
at Object.<anonymous> (/drivers/switch/flows.js:44:37)
at emitThree (events.js:102:20)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:194
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

Send a log 08181EE31A

**Comment by posthok** [comment]
@caseda Turning off the power, wait a few minutes and start again. This helps.

**Comment by caseda** [comment]
This did not work for me, like I mentioned in my previous post.
Had it off the power for atleast 10 minutes

**Comment by posthok** [comment]
@caseda yes you are right still doesn't right
@Dennishacq whe have still a problem with 1.15.
TypeError: Cannot read property 'variables' of undefined
at Object.module.exports.self.capabilities.alarm_contact.get (/drivers/switch/driver.js:129:28)
at Object.<anonymous> (/drivers/switch/flows.js:51:39)
at emitThree (events.js:102:20)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:194
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7),TypeError: Cannot read property 'variables' of undefined
at Object.module.exports.self.capabilities.alarm_motion.get (/drivers/switch/driver.js:117:28)
at Object.<anonymous> (/drivers/switch/flows.js:37:38)
at emitThree (events.js:102:20)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:194
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

removing sensors an readding them brings no solution.

**Comment by Dennishacq** [comment]
Hey guys, this is indeed a bug that still exists in v1.0.5.
I'm working on a fix that should be online later today.

**Comment by posthok** [comment]
great thanx

**Comment by Dennishacq** [comment]
The update is online ;)

**Comment by posthok** [comment]
Yes Thanx updated the app allready.

**Comment by caseda** [comment]
Already did notice it.
And it fixes the bug perfectly (YAY!)

Thank you @Dennishacq for these quick fixes

**Comment by posthok** [comment]
Did a quick test. Everything is working again. Thanx Dennis!!!

**Comment by Dennishacq** [comment]
I'm very glad to hear it's working again. Sorry for the inconvenience guys!

**Comment by posthok** [comment]
![boton_me_gusta svg](https://cloud.githubusercontent.com/assets/6661318/16130297/b8bf0b12-3408-11e6-81af-388091701011.png)
