### ISSUE TITLE
Homey Doesn't remember 433mhz Device state

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#700]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

I've noticed that when i run a flow either time based or trigger based (Kaku Remote) Homey doesn't remember in which position the 433mhz device is. The GUI I can switch device A on but it forgot's it's state when i go back.

Example:
Device Switch Waaklamp is off, I switch the Switch Waaklamp on by pressing the button in the GUI the devices switches on (also works with timed/action flows). When i close this window and reopen this again, the device show it's status as off while it should be displayed as on.

![schermafbeelding 2016-06-22 om 23 13 31](https://cloud.githubusercontent.com/assets/17526110/16284036/98eaa992-38cf-11e6-95ec-279d21be9f37.png)

The switch also doesn't reflect the "on" position if switched with a timed/action flow.

**What was the result?**

Device status is displayed incorrect, last action was switched on, it should therefore be in the on position.

**What did you expect as result?**

See above.

**Any other remarks**

Issue with the IOS App, GUI on chrome and the app.

**Comment by Arjanvde** [comment]
It looks like it remembers the correct state for the Action switches but not for the Smartwares switches.

**Comment by btwvince** [comment]
I think I have the same issue, my night sensor is set 1 time to on and now it stays on. So my flows bassed on that sensor won't work either

**Comment by Arjanvde** [comment]
Well that could be a cause that if a flow checks if the sensor is on/off and the status isn't adjusted in the interface all these flow's won't work probably.

**Comment by BasKiers** [comment]
Should be fixed with the new 2.x versions of apps. If not please reopen this issue. The issue with the night sensor will be investigated under #708 .

**Comment by Arjanvde** [comment]
Can be closed, thanks!

**Comment by Fiek1** [comment]
The device state is still not remembered by Homey with the new app

**Comment by btwvince** [comment]
I have the same problem with my night sensor from kaku. It is send to on for one time but now it stays in the on-state.
