### ISSUE TITLE
[KAKU][0.8.39] KaKu not responding 

### ISSUE THREAD

**Issue by scanno** [athombv/homey#704]
**What is your Homey version (Settings → System)?**

0.8.39 and KaKu 1.1.6

**What did you try to achieve?**

Switching on and off my lights with KaKu

**What was the result?**

Nothing. Lights do not switch on or off. After trying a few times, homey crashes (ERR_CONNECTION_RESET by trying to connect locally on the local IP adress)

**What did you expect as result?**

Lights switching on or off and Homey not crashing

**Any other remarks**

I removed the KaKu app and reinstalled it. All Kaku devices were gone and tried to add a KaKu device again. Signal is not received by Homey. By trying to add the Kaku dimmer by using the Kaku remote only works within 2 meters. Right after this, Homey crashed again.

Oh and i did the "Pull the Plug" already a few times without any success.

On Previous firmwares KaKu was working great. Since the .39 upgrade KaKu never worked, and Homey cannot be accessed any more.

**Comment by scanno** [comment]
Did a complete reset of homey, but the above problem remains.  Somehow signals from homey are nit received by Kaku. Even if honey is in the same room.

**Comment by Vortjong** [comment]
Have almost the same issue. Adding a new device using learning works, but when swithing on/off using homey nothing responds.

**Comment by maaikekaasenbrood** [comment]
I also have the same problem (using the ELRO app). In 0.8.32 the output always worked, KaKu as input 70% of the times. But with 0.8.39 both input and output do not work anymore. And as stated above the learning functionality does work.

**Comment by scanno** [comment]
Also with the new app (2.0.2) this problem still exists. Besides that the AWMR-230 and the AWMD-250 are not in the list of KaKu devices.

**Comment by maaikekaasenbrood** [comment]
With the new app, the Elro remote with sockets works like a charm. The remote is recognized as one device with 8 buttons a huge improvement, and Homey recognized the pushed buttons let's say 99% of the time.

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.9.0

**Comment by scanno** [comment]
not really solved. https://github.com/athombv/homey/issues/729 by request of BasKiers. i guess the crashing is gone, but i am not testing that.

**Comment by jeroenvollenbrock** [comment]
Hi Menno, thanks again for helping us solve this issue!
