### ISSUE TITLE
Homey not connected to Athom cloud

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#727]
**What is your Homey version (Settings → System)?**

 0.8.39

**What did you try to achieve?**

Once in a while when I open up the homey settings or flow a little icon is shown with a text that Homey is not connected to the athom cloud. 

**What was the result?**
Not available from the internet

**What did you expect as result?**

able to change settings from the office

**Any other remarks**

Apps installed: 

Betere stem 0.0.1
KlikaanKlikuit 2.0.1
Better Logic 0.9.5
Pathe bioscoop agenda 1.0.3
GPS-Trace 0.3.2
HTTP Request flow chards 1.2.1
RSS Reader 0.0.1
Wake on Lan 1.0.2

**Comment by nattlip** [comment]
i have the same cold reboot via another domotica system (plugwise source server) resolves the issue temporarely

**Comment by jeroenvollenbrock** [comment]
Possibly fixed in 0.9.0, could you please re-test and post your findings (after 0.9.0 has been released?)

**Comment by Inversion-NL** [comment]
Do you need anything from me while it's still not connected to the cloud @jeroenvollenbrock @WeeJeWel @goldenice 
Don't want to have it another 4 days being unconnected to the Athom Cloud since I'm now not able to use the mobile app while not at home, receive push notifications on my phones and open Homey's website while not at home.

**Comment by jeroenvollenbrock** [comment]
brcmfmac Kernel oops during group rekeying (GTK=CCMP)
Full log at abrt/0.0.0/1471605930427

@WeeJeWel: The kernel managed to recover, but homey stopped its cloud reconnection attempts. Maybe change the retry process or use a different strategy (exponential backoff?)
