### ISSUE TITLE
Sunrise/Sunset not working reliable

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/homey#8]

**Comment by WeeJeWel** [comment]
Fixed in 0.8.7

**Comment by JPe2** [comment]
Closed? But still existing in 0.8.29, please reopen or better solve the problem.

**Comment by WeeJeWel** [comment]
See https://github.com/athombv/homey/issues/182
