### ISSUE TITLE
Z-Wave trigger on action does not work.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#811]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

On previous versions I had a flow running that if the light in the hallway was switched on, i would receive a push notification on Slack that the Light was switched on. Since .8.39 and upwards the combination of these flows are not working anymore.

Note, the Z-Wave devices are added as a basic device.

![flow not working](https://cloud.githubusercontent.com/assets/17526110/17883663/295ec78c-6914-11e6-8b26-2902840bf568.png)

In this case the switch is triggered by a timed flow, even if I switch the Z-Wave device through the devices screen this flows are not working.

**What was the result?**

I was expecting a message but that didn't come.

**Comment by Inversion-NL** [comment]
I'm sorry if you did test it but are you able to post to Slack if you press test?

**Comment by Arjanvde** [comment]
@Inversion-NL , Pressing test gives a message on Slack. Triggering the switch doesn't.

Could also be tested with a push notification, but can also be related with #810  since the device stated is not remembered.

**Comment by Inversion-NL** [comment]
Ah, just checking 😊

**Comment by jeroenvollenbrock** [comment]
Might be related to #810

**Comment by Arjanvde** [comment]
My thoughts exactly..

**Comment by freemann** [comment]
and something to do with;
https://github.com/athombv/homey/issues/801
?

**Comment by jeroenvollenbrock** [comment]
No.

**Comment by freemann** [comment]
ah ok :+1:

**Comment by WeeJeWel** [comment]
Fixed in 0.9.3

**Comment by Arjanvde** [comment]
Sorry to say, trigger still doesn't work for a Generic Z-Wave device. Does work for a known Z-Wave device like the Fibaro Wall plug.

**Comment by WeeJeWel** [comment]
Should be fixed in 0.10.0

**Comment by Arjanvde** [comment]
Can't check this unfortunately anymore, will close this for now.
