### ISSUE TITLE
Device Settings type "Label" showing error for value type when validating for appstore

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#838]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Validate and enter the magister app for appstore release

*Please include detailed steps how we can reproduce the issue*

use type label, and define a value string in app.json:

```"children": [
            {
              "id": "studentName",
              "type": "label",
              "label": {
                "en": "Studentname",
                "nl": "Studentnaam"
              },
              "value": "student" ```


**What was the result?**

When I try to validate for app store release I get an error. 

```App failed to validate!
Error: invalid type for driver[0].settings[0].children[0].value in app.json, expected type undefined```


**What did you expect as result?**

the app to be validated as correct, and being able to upload to the appstore

**Any other remarks**

the app runs fine when installing in debug mode.
see also #760
...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by gruijter** [comment]
@jeroenvollenbrock  just tried to update my apps in the store, but the error persists...

**Comment by joachimroeleveld** [comment]
Hi @gruijter, this should be resolved now. Can you verify this?

**Comment by gruijter** [comment]
No, still an error

Oops! Your app did not pass our validation process. The following errors occurred:
invalid type for `driver[0].settings[0].children[0].value` in app.json, expected type undefined

**Comment by gruijter** [comment]
@joachimroeleveld : now it works! Thx!

**Comment by joachimroeleveld** [comment]
@gruijter good to hear!
