### ISSUE TITLE
Flow does not continue

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#893]
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**

Build a flow

**What was the result?**

I have a number of flows where the "then" cards are not ALL executed. Some with a huge delay others not at all.

**What did you expect as result?**

That all then actions will be executed without a delay.

**Any other remarks**

**Comment by bvdbos** [comment]
Hoe many and which cards do you have for the action? And do they have delays? Does this only happen with the test-button? Is it always the same cards not working?

**Comment by magtimmermans** [comment]
Hi, 

They all have to with the shutters (SOMFY). When I use them as an app and put the shutter down it works always. But when I use them in a flow. Sometimes it works. Mostly not. Sometimes delayed (up to a minute). All shutters should go down at the same time. There is a delay on the stop command of each shutter. In the previous version everything worked great.

![2016-09-18 16_20_30-](https://cloud.githubusercontent.com/assets/17949840/18817049/c593e3ba-8356-11e6-9058-bfc3edd63d4d.png)

**Comment by Arjanvde** [comment]
Can confirm that this also happens for the brightness on Philips HUE. It sets the brightness, (on the test button the circle keeps spinning) and the flow doesn't continue.

**Comment by Phunkay** [comment]
I found that delays are added up. Cards will be executed with the combined delays of all previous cards.

**Comment by magtimmermans** [comment]
Oeps

**Comment by bvdbos** [comment]
Oeps on one hand but sounds like an easy fix codewise :+1:

**Comment by magtimmermans** [comment]
Indeed!

**Comment by WeeJeWel** [comment]
Whoops indeed. Thanks so much for figuring that out!

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1

**Comment by bvdbos** [comment]
confirmed, fixed for me. This works perfectly. Is it fixed for you too @magtimmermans ?
![eerste nummer starten](https://cloud.githubusercontent.com/assets/1064079/19019326/8a8845e4-8884-11e6-9ff6-ed379b8720ab.png)

**Comment by magtimmermans** [comment]
fixed

**Comment by MdeRhoter** [comment]
Action cards that set brightness (Kaku / Hue) still don't work properly!

**Comment by bvdbos** [comment]
@MdeRhoter isn't that issue #934 ?

**Comment by MdeRhoter** [comment]
Yes it is - well spotted! Thanks 👍
