### ISSUE TITLE
No lights found: APA3-1500R KAKU

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#968]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
I connected two APA3-1500R KAKU devices, assign them as lights.

I tried to turn off/on the lights, for example: "Turn (on/off) the lights" or "Turn on the lights in the livingroom". 

*Please include detailed steps how we can reproduce the issue*

-Connect a APA3-1500R KAKU Device
-Set device as light
-Assign the light to a zone
-Say to Homey: "Turn off the lights"

**What was the result?**
Homey says: "No lights found".

**What did you expect as result?**
Recognise these devices as lights, so i can switch them on/off.

**Any other remarks**
Same bug as #909?

**Comment by mike9011** [comment]
When i say "zet alle stopcontacten uit" it works.

**Comment by SimNL** [comment]
I also have the same issue.
When I add a KaKu device (AWMR-230) and, during the add-device-wizard, assign it as a light, it seems Homey doesn't properly save it as a light(but just as a device).

When, for instance, I say "Turn the lights off", Homey responds with "No lights found".

This also brings up the question if it is possible to change the device type(light, fan, heater, etc) after the device has been added?

**Comment by WeeJeWel** [comment]
Hm, we cannot seem to reproduce the issue. Can you post a screenshot of your Zones & Devices screen?

**Comment by SimNL** [comment]
![homeydevices](https://cloud.githubusercontent.com/assets/4105229/19274839/de2faf3a-8fd1-11e6-839a-3759ea5f3a2e.png)

I also tried adding the device as a fan or a heather, but it seems the device type isn't saved at all.

**Comment by WeeJeWel** [comment]
We've found a bug in the KlikAanKlikUit app that when the step 'What is plugged in' in the pair wizard is clicked too soon, this is not applied. We're working on a workaround, in the meantime, take it slow, it might work :-)

@SimNL The icon for 'Eurodomest' shows a socket, which wouldn't work as a light, so that makes sense.

**Comment by SimNL** [comment]
Yeah I know, the Eurodomest-device is a socket, but the AWMR is connected to the ceiling light in the living room and added as such :) 
But thanks for the workaround, I will try it as soon as I get home!

**Comment by mike9011** [comment]
@WeeJeWel Still have this issue? Since this one is closed, but issue #991 also?
The workaround doesnt work for me either, waited 2 minutes before i assigned it as lamp.. but not working.

**Comment by BasKiers** [comment]
Hi, 

I've fixed this issue yesterday. Could you please try again with kaku v2.6.4 or greater?

Regards,
Bas

**Comment by mike9011** [comment]
Great! Issue is solved! Thank you very much!

**Comment by mglat** [comment]
Looks like the issue is back. It has been working always, but since 2 days the response of homey is "no lights found"
